export const iconMapping: Record<string, string> = {
  // A
  activitypub: "simple-icons:activitypub",
  actix: "simple-icons:actix",
  adonis: "logos:adonisjs-icon",
  ae: "simple-icons:adobeaftereffects",
  alpinejs: "logos:alpinejs-icon",
  anaconda: "simple-icons:anaconda",
  androidstudio: "simple-icons:androidstudio",
  angular: "logos:angular-icon",
  ansible: "logos:ansible",
  apollo: "simple-icons:apollographql",
  apple: "logos:apple",
  appwrite: "logos:appwrite",
  arch: "logos:archlinux",
  arduino: "logos:arduino",
  astro: "logos:astro-icon",
  atom: "logos:atom",
  au: "simple-icons:adobeaudition",
  autocad: "simple-icons:autocad",
  aws: "devicon:amazonwebservices",
  azul: "logos:azul",
  azure: "devicon:azure",

  // B
  babel: "logos:babel",
  bash: "logos:bash",
  bevy: "simple-icons:bevy",
  bitbucket: "logos:bitbucket",
  blender: "logos:blender",
  bootstrap: "logos:bootstrap",
  bsd: "logos:freebsd",
  bun: "logos:bun",

  // C
  c: "logos:c",
  cs: "logos:c-sharp",
  cpp: "logos:c-plusplus",
  crystal: "logos:crystal",
  cassandra: "simple-icons:apachecassandra",
  clion: "logos:clion",
  clojure: "logos:clojure",
  cloudflare: "logos:cloudflare",
  cmake: "simple-icons:cmake",
  codepen: "devicon:codepen",
  coffeescript: "logos:coffeescript",
  css: "logos:css-3",
  cypress: "logos:cypress-icon",

  // D
  d3: "simple-icons:d3dotjs",
  dart: "logos:dart",
  debian: "logos:debian",
  deno: "logos:deno",
  devto: "simple-icons:devdotto",
  discord: "simple-icons:discord",
  bots: "simple-icons:discord",
  discordjs: "logos:discordjs",
  django: "logos:django-icon",
  docker: "logos:docker-icon",
  dotnet: "logos:dotnet",
  dynamodb: "logos:aws-dynamodb",

  // E
  eclipse: "logos:eclipseide",
  elasticsearch: "logos:elasticsearch",
  electron: "logos:electron",
  elixir: "devicon:elixir",
  emacs: "simple-icons:gnuemacs",
  ember: "logos:ember",
  express: "logos:express",

  // F
  fastapi: "logos:fastapi",
  fediverse: "logos:fediverse",
  figma: "logos:figma",
  firebase: "logos:firebase-icon",
  flask: "logos:flask",
  flutter: "logos:flutter",
  fortran: "logos:fortran",

  // G
  gamemakerstudio: "simple-icons:gamemaker",
  gatsby: "logos:gatsby",
  gcp: "simple-icons:googlecloud",
  git: "logos:git-icon",
  github: "logos:github-icon",
  githubactions: "simple-icons:githubactions",
  gitlab: "logos:gitlab-icon",
  gmail: "simple-icons:gmail",
  go: "logos:go",
  gradle: "logos:gradle",
  godot: "simple-icons:godotengine",
  grafana: "logos:grafana",
  graphql: "logos:graphql",
  gtk: "simple-icons:gtk",
  gulp: "logos:gulp",

  // H
  haskell: "logos:haskell",
  haxe: "logos:haxe",
  heroku: "logos:heroku-icon",
  hibernate: "logos:hibernate",
  html: "logos:html-5",
  htmx: "logos:htmx",

  // I
  idea: "simple-icons:intellijidea",
  ai: "simple-icons:adobeillustrator",
  instagram: "logos:instagram",
  ipfs: "simple-icons:ipfs",

  // J
  java: "logos:java",
  js: "logos:javascript",
  jenkins: "logos:jenkins",
  jest: "logos:jest",
  jquery: "logos:jquery",

  // K
  kafka: "simple-icons:apachekafka",
  kali: "simple-icons:kalilinux",
  kotlin: "logos:kotlin",
  ktor: "logos:ktor",
  kubernetes: "logos:kubernetes",

  // L
  laravel: "logos:laravel",
  latex: "simple-icons:latex",
  less: "logos:less",
  linkedin: "devicon:linkedin",
  linux: "simple-icons:linux",
  lit: "logos:lit",
  lua: "logos:lua",

  // M
  md: "logos:markdown",
  mastodon: "logos:mastodon",
  materialui: "simple-icons:mui",
  matlab: "devicon:matlab",
  maven: "simple-icons:apachemaven",
  mint: "simple-icons:linuxmint",
  misskey: "simple-icons:misskey",
  mongodb: "logos:mongodb-icon",
  mysql: "logos:mysql",

  // N
  neovim: "logos:neovim",
  nestjs: "logos:nestjs",
  netlify: "logos:netlify-icon",
  nextjs: "logos:nextjs-icon",
  nginx: "logos:nginx",
  nim: "devicon:nim",
  nix: "simple-icons:nixos",
  nodejs: "logos:nodejs-icon",
  notion: "logos:notion",
  npm: "logos:npm-icon",
  nuxtjs: "logos:nuxt-icon",

  // O
  obsidian: "logos:obsidian",
  ocaml: "logos:ocaml",
  octave: "simple-icons:octave",
  opencv: "simple-icons:opencv",
  openshift: "logos:redhatopenshift",
  openstack: "logos:openstack",

  // P
  p5js: "logos:p5js",
  perl: "logos:perl",
  ps: "simple-icons:adobephotoshop",
  php: "logos:php",
  phpstorm: "logos:phpstorm",
  pinia: "logos:pinia",
  pkl: "logos:pkl",
  plan9: "logos:plan9",
  planetscale: "logos:planetscale",
  pnpm: "logos:pnpm",
  postgres: "logos:postgresql",
  postman: "logos:postman",
  powershell: "devicon:powershell",
  pr: "simple-icons:adobepremierepro",
  prisma: "logos:prisma",
  processing: "logos:processing",
  prometheus: "logos:prometheus",
  pug: "logos:pug",
  pycharm: "logos:pycharm",
  py: "logos:python",
  pytorch: "logos:pytorch",

  // Q
  qt: "logos:qt",

  // R
  r: "logos:r-lang",
  rabbitmq: "logos:rabbitmq",
  rails: "logos:rails",
  raspberrypi: "simple-icons:raspberrypi",
  react: "logos:react",
  reactivex: "logos:reactivex",
  redhat: "logos:redhat",
  redis: "logos:redis",
  redux: "logos:redux",
  regex: "devicon:regex",
  remix: "logos:remix",
  replit: "logos:replit",
  rider: "logos:rider",
  robloxstudio: "logos:robloxstudio",
  rocket: "simple-icons:rocket",
  rollupjs: "logos:rollupjs",
  ros: "logos:ros",
  ruby: "logos:ruby",
  rust: "logos:rust",

  // S
  sass: "logos:sass",
  spring: "logos:spring-icon",
  sqlite: "logos:sqlite",
  stackoverflow: "logos:stackoverflow",
  styledcomponents: "simple-icons:styledcomponents",
  sublime: "logos:sublimetext",
  supabase: "logos:supabase-icon",
  scala: "logos:scala",
  sklearn: "simple-icons:scikitlearn",
  selenium: "logos:selenium",
  sentry: "logos:sentry",
  sequelize: "logos:sequelize",
  sketchup: "simple-icons:sketchup",
  solidity: "logos:solidity",
  solidjs: "logos:solidjs",
  svelte: "logos:svelte-icon",
  svg: "logos:svg",
  swift: "logos:swift",
  symfony: "logos:symfony",

  // T
  tailwind: "logos:tailwindcss-icon",
  tauri: "logos:tauri",
  tensorflow: "logos:tensorflow",
  terraform: "logos:terraform",
  threejs: "logos:threejs",
  twitter: "devicon:twitter",
  ts: "logos:typescript-icon",

  // U
  ubuntu: "logos:ubuntu",
  unity: "logos:unity",
  unreal: "logos:unrealengine",

  // V
  v: "simple-icons:v",
  vala: "devicon:vala",
  vercel: "logos:vercel-icon",
  vim: "logos:vim",
  visualstudio: "devicon:visualstudio",
  vite: "simple-icons:vite",
  vitest: "logos:vitest",
  vscode: "devicon:vscode",
  vscodium: "simple-icons:vscodium",
  vue: "logos:vue",
  vuetify: "simple-icons:vuetify",

  // W
  wasm: "logos:webassembly",
  webflow: "logos:webflow",
  webpack: "logos:webpack",
  webstorm: "logos:webstorm",
  windicss: "simple-icons:windicss",
  windows: "simple-icons:windows",
  wordpress: "logos:wordpress",
  workers: "simple-icons:cloudflareworkers",

  // X-Y-Z
  xd: "simple-icons:adobexd",
  yarn: "logos:yarn",
  zig: "logos:zig",
};

export function getIconifyIcon(skillIconId: string): string {
  return iconMapping[skillIconId.toLowerCase()] || `logos:${skillIconId}`;
}
