export const techLinks: Record<string, string> = {
  javascript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  typescript: "https://www.typescriptlang.org/",
  python: "https://www.python.org/",
  java: "https://www.java.com/",
  go: "https://go.dev/",
  rust: "https://www.rust-lang.org/",
  c: "https://en.cppreference.com/w/c",
  cpp: "https://en.cppreference.com/w/cpp",
  cs: "https://docs.microsoft.com/en-us/dotnet/csharp/",
  ruby: "https://www.ruby-lang.org/",
  php: "https://www.php.net/",
  swift: "https://www.swift.org/",
  kotlin: "https://kotlinlang.org/",
  dart: "https://dart.dev/",
  scala: "https://www.scala-lang.org/",
  r: "https://www.r-project.org/",
  bash: "https://www.gnu.org/software/bash/",
  lua: "https://www.lua.org/",
  perl: "https://www.perl.org/",
  elixir: "https://elixir-lang.org/",
  clojure: "https://clojure.org/",
  haskell: "https://www.haskell.org/",

  react: "https://react.dev/",
  vue: "https://vuejs.org/",
  angular: "https://angular.io/",
  svelte: "https://svelte.dev/",
  nextjs: "https://nextjs.org/",
  nuxtjs: "https://nuxt.com/",
  gatsby: "https://www.gatsbyjs.com/",
  remix: "https://remix.run/",
  astro: "https://astro.build/",
  solidjs: "https://www.solidjs.com/",

  nodejs: "https://nodejs.org/",
  express: "https://expressjs.com/",
  nestjs: "https://nestjs.com/",
  fastapi: "https://fastapi.tiangolo.com/",
  django: "https://www.djangoproject.com/",
  flask: "https://flask.palletsprojects.com/",
  spring: "https://spring.io/",
  laravel: "https://laravel.com/",
  rails: "https://rubyonrails.org/",

  tailwind: "https://tailwindcss.com/",
  bootstrap: "https://getbootstrap.com/",
  materialui: "https://mui.com/",
  sass: "https://sass-lang.com/",

  jest: "https://jestjs.io/",
  vitest: "https://vitest.dev/",
  cypress: "https://www.cypress.io/",
  selenium: "https://www.selenium.dev/",

  vite: "https://vitejs.dev/",
  webpack: "https://webpack.js.org/",
  rollupjs: "https://rollupjs.org/",
  bun: "https://bun.sh/",

  aws: "https://aws.amazon.com/",
  azure: "https://azure.microsoft.com/",
  gcp: "https://cloud.google.com/",
  vercel: "https://vercel.com/",
  netlify: "https://www.netlify.com/",
  cloudflare: "https://www.cloudflare.com/",
  heroku: "https://www.heroku.com/",

  mongodb: "https://www.mongodb.com/",
  postgres: "https://www.postgresql.org/",
  mysql: "https://www.mysql.com/",
  redis: "https://redis.io/",
  sqlite: "https://www.sqlite.org/",
  cassandra: "https://cassandra.apache.org/",
  elasticsearch: "https://www.elastic.co/",

  docker: "https://www.docker.com/",
  kubernetes: "https://kubernetes.io/",
  jenkins: "https://www.jenkins.io/",
  githubactions: "https://github.com/features/actions",
  gitlab: "https://about.gitlab.com/",
  terraform: "https://www.terraform.io/",
  ansible: "https://www.ansible.com/",

  git: "https://git-scm.com/",
  github: "https://github.com/",

  vscode: "https://code.visualstudio.com/",
  vim: "https://www.vim.org/",
  neovim: "https://neovim.io/",
  idea: "https://www.jetbrains.com/idea/",
  webstorm: "https://www.jetbrains.com/webstorm/",
  pycharm: "https://www.jetbrains.com/pycharm/",
  phpstorm: "https://www.jetbrains.com/phpstorm/",

  graphql: "https://graphql.org/",
  prisma: "https://www.prisma.io/",
  firebase: "https://firebase.google.com/",
  supabase: "https://supabase.com/",
  figma: "https://www.figma.com/",
  postman: "https://www.postman.com/",

  reactnative: "https://reactnative.dev/",
  flutter: "https://flutter.dev/",
  ionic: "https://ionicframework.com/",
  xamarin: "https://dotnet.microsoft.com/apps/xamarin",

  electron: "https://www.electronjs.org/",
  tauri: "https://tauri.app/",

  redux: "https://redux.js.org/",
  mobx: "https://mobx.js.org/",
  zustand: "https://zustand-demo.pmnd.rs/",
  recoil: "https://recoiljs.org/",

  rest: "https://restfulapi.net/",
  grpc: "https://grpc.io/",
  trpc: "https://trpc.io/",
  socketio: "https://socket.io/",

  auth0: "https://auth0.com/",
  okta: "https://www.okta.com/",
  clerk: "https://clerk.dev/",

  contentful: "https://www.contentful.com/",
  strapi: "https://strapi.io/",
  sanity: "https://www.sanity.io/",
  wordpress: "https://wordpress.org/",

  playwright: "https://playwright.dev/",
  testinglibrary: "https://testing-library.com/",
  mocha: "https://mochajs.org/",
  jasmine: "https://jasmine.github.io/",

  sentry: "https://sentry.io/",
  datadog: "https://www.datadoghq.com/",
  newrelic: "https://newrelic.com/",
  prometheus: "https://prometheus.io/",
  grafana: "https://grafana.com/",

  npm: "https://www.npmjs.com/",
  yarn: "https://yarnpkg.com/",
  pnpm: "https://pnpm.io/",

  babel: "https://babeljs.io/",
  esbuild: "https://esbuild.github.io/",
  swc: "https://swc.rs/",
  parcel: "https://parceljs.org/",

  less: "https://lesscss.org/",
  stylus: "https://stylus-lang.com/",
  postcss: "https://postcss.org/",
  styledcomponents: "https://styled-components.com/",
  emotion: "https://emotion.sh/",
  chakraui: "https://chakra-ui.com/",
  antdesign: "https://ant.design/",

  mariadb: "https://mariadb.org/",
  neo4j: "https://neo4j.com/",
  dynamodb: "https://aws.amazon.com/dynamodb/",
  supabasedb: "https://supabase.com/database",
  planetscale: "https://planetscale.com/",

  sequelize: "https://sequelize.org/",
  typeorm: "https://typeorm.io/",
  drizzle: "https://orm.drizzle.team/",
  knex: "https://knexjs.org/",

  rabbitmq: "https://www.rabbitmq.com/",
  kafka: "https://kafka.apache.org/",

  nginx: "https://nginx.org/",
  apache: "https://httpd.apache.org/",

  eslint: "https://eslint.org/",
  prettier: "https://prettier.io/",
  husky: "https://typicode.github.io/husky/",

  linux: "https://www.linux.org/",
  ubuntu: "https://ubuntu.com/",
  debian: "https://www.debian.org/",
  alpine: "https://www.alpinelinux.org/",
  centos: "https://www.centos.org/",
  windows: "https://www.microsoft.com/windows",
  macos: "https://www.apple.com/macos/",

  html: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  css: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  svg: "https://developer.mozilla.org/en-US/docs/Web/SVG",
  json: "https://www.json.org/",
  yaml: "https://yaml.org/",
  xml: "https://www.w3.org/XML/",

  tensorflow: "https://www.tensorflow.org/",
  pytorch: "https://pytorch.org/",
  scikitlearn: "https://scikit-learn.org/",
  pandas: "https://pandas.pydata.org/",
  numpy: "https://numpy.org/",
  jupyter: "https://jupyter.org/",

  unity: "https://unity.com/",
  unreal: "https://www.unrealengine.com/",
  godot: "https://godotengine.org/",

  solidity: "https://soliditylang.org/",
  ethereum: "https://ethereum.org/",
  web3js: "https://web3js.org/",

  regex: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions",
  markdown: "https://www.markdownguide.org/",
  latex: "https://www.latex-project.org/",
};

export function getTechLink(techId: string, techName: string): string {
  return techLinks[techId.toLowerCase()] || `https://simpleicons.org/?q=${encodeURIComponent(techName)}`;
}
