import type { TechId, TechItem } from "./types";
import { TechCategory } from "./types";

/**
 * Tech Stack Data
 *
 * Single source of truth for all technology information.
 * Includes icon mappings and links in one place.
 *
 * @see https://icon-sets.iconify.design/ for available icons
 */
export const TECH_STACK = {
  "adonis": {
    id: "adonis",
    name: "AdonisJS",
    category: TechCategory.Framework,
    iconify: "logos:adonisjs-icon",
  },
  "alpinejs": {
    id: "alpinejs",
    name: "Alpine.js",
    category: TechCategory.Framework,
    iconify: "logos:alpinejs-icon",
  },
  "angular": {
    id: "angular",
    name: "Angular",
    category: TechCategory.Framework,
    iconify: "logos:angular-icon",
    link: "https://angular.io/",
  },
  "ansible": {
    id: "ansible",
    name: "Ansible",
    category: TechCategory.Platform,
    iconify: "logos:ansible",
    link: "https://www.ansible.com/",
  },
  "apple": {
    id: "apple",
    name: "Apple",
    category: TechCategory.Platform,
    iconify: "logos:apple",
  },
  "appwrite": {
    id: "appwrite",
    name: "Appwrite",
    category: TechCategory.Cloud,
    iconify: "logos:appwrite",
  },
  "arch": {
    id: "arch",
    name: "Arch Linux",
    category: TechCategory.Platform,
    iconify: "logos:archlinux",
  },
  "arduino": {
    id: "arduino",
    name: "Arduino",
    category: TechCategory.Platform,
    iconify: "logos:arduino",
  },
  "astro": {
    id: "astro",
    name: "Astro",
    category: TechCategory.Framework,
    iconify: "logos:astro-icon",
    link: "https://astro.build/",
  },
  "atom": {
    id: "atom",
    name: "Atom",
    category: TechCategory.Platform,
    iconify: "logos:atom",
  },
  "aws": {
    id: "aws",
    name: "Amazon Web Services",
    category: TechCategory.Cloud,
    iconify: "logos:aws",
    link: "https://aws.amazon.com/",
  },
  "azure": {
    id: "azure",
    name: "Microsoft Azure",
    category: TechCategory.Cloud,
    iconify: "logos:azure",
    link: "https://azure.microsoft.com/",
  },
  "babel": {
    id: "babel",
    name: "Babel",
    category: TechCategory.Library,
    iconify: "logos:babel",
    link: "https://babeljs.io/",
  },
  "bash": {
    id: "bash",
    name: "Bash",
    category: TechCategory.Language,
    iconify: "logos:bash",
    link: "https://www.gnu.org/software/bash/",
  },
  "bitbucket": {
    id: "bitbucket",
    name: "Bitbucket",
    category: TechCategory.CICD,
    iconify: "logos:bitbucket",
  },
  "blender": {
    id: "blender",
    name: "Blender",
    category: TechCategory.Other,
    iconify: "logos:blender",
  },
  "bootstrap": {
    id: "bootstrap",
    name: "Bootstrap",
    category: TechCategory.Library,
    iconify: "logos:bootstrap",
    link: "https://getbootstrap.com/",
  },
  "bsd": {
    id: "bsd",
    name: "BSD",
    category: TechCategory.Platform,
    iconify: "logos:freebsd",
  },
  "bun": {
    id: "bun",
    name: "Bun",
    category: TechCategory.Platform,
    iconify: "logos:bun",
    link: "https://bun.sh/",
  },
  "c": {
    id: "c",
    name: "C",
    category: TechCategory.Language,
    iconify: "logos:c",
    link: "https://en.cppreference.com/w/c",
  },
  "cs": {
    id: "cs",
    name: "C#",
    category: TechCategory.Language,
    iconify: "logos:c-sharp",
    link: "https://docs.microsoft.com/en-us/dotnet/csharp/",
  },
  "cpp": {
    id: "cpp",
    name: "C++",
    category: TechCategory.Language,
    iconify: "logos:c-plusplus",
    link: "https://en.cppreference.com/w/cpp",
  },
  "crystal": {
    id: "crystal",
    name: "Crystal",
    category: TechCategory.Language,
    iconify: "logos:crystal",
  },
  "clion": {
    id: "clion",
    name: "CLion",
    category: TechCategory.Platform,
    iconify: "logos:clion",
  },
  "clojure": {
    id: "clojure",
    name: "Clojure",
    category: TechCategory.Language,
    iconify: "logos:clojure",
    link: "https://clojure.org/",
  },
  "cloudflare": {
    id: "cloudflare",
    name: "Cloudflare",
    category: TechCategory.Cloud,
    iconify: "logos:cloudflare",
    link: "https://www.cloudflare.com/",
  },
  "codepen": {
    id: "codepen",
    name: "CodePen",
    category: TechCategory.Platform,
    iconify: "logos:codepen",
  },
  "coffeescript": {
    id: "coffeescript",
    name: "CoffeeScript",
    category: TechCategory.Language,
    iconify: "logos:coffeescript",
  },
  "css": {
    id: "css",
    name: "CSS",
    category: TechCategory.Language,
    iconify: "logos:css-3",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  "cypress": {
    id: "cypress",
    name: "Cypress",
    category: TechCategory.Library,
    iconify: "logos:cypress-icon",
    link: "https://www.cypress.io/",
  },
  "dart": {
    id: "dart",
    name: "Dart",
    category: TechCategory.Language,
    iconify: "logos:dart",
    link: "https://dart.dev/",
  },
  "debian": {
    id: "debian",
    name: "Debian",
    category: TechCategory.Platform,
    iconify: "logos:debian",
    link: "https://www.debian.org/",
  },
  "deno": {
    id: "deno",
    name: "Deno",
    category: TechCategory.Platform,
    iconify: "logos:deno",
  },
  "discordjs": {
    id: "discordjs",
    name: "Discord.js",
    category: TechCategory.Library,
    iconify: "logos:discord",
  },
  "django": {
    id: "django",
    name: "Django",
    category: TechCategory.Framework,
    iconify: "logos:django-icon",
    link: "https://www.djangoproject.com/",
  },
  "docker": {
    id: "docker",
    name: "Docker",
    category: TechCategory.Platform,
    iconify: "logos:docker-icon",
    link: "https://www.docker.com/",
  },
  "dotnet": {
    id: "dotnet",
    name: ".NET",
    category: TechCategory.Framework,
    iconify: "logos:dotnet",
  },
  "dynamodb": {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    category: TechCategory.Database,
    iconify: "logos:aws-dynamodb",
    link: "https://aws.amazon.com/dynamodb/",
  },
  "elasticsearch": {
    id: "elasticsearch",
    name: "Elasticsearch",
    category: TechCategory.Database,
    iconify: "logos:elasticsearch",
    link: "https://www.elastic.co/",
  },
  "electron": {
    id: "electron",
    name: "Electron",
    category: TechCategory.Framework,
    iconify: "logos:electron",
    link: "https://www.electronjs.org/",
  },
  "ember": {
    id: "ember",
    name: "Ember.js",
    category: TechCategory.Framework,
    iconify: "logos:ember",
  },
  "express": {
    id: "express",
    name: "Express.js",
    category: TechCategory.Framework,
    iconify: "logos:express",
    link: "https://expressjs.com/",
  },
  "fastapi": {
    id: "fastapi",
    name: "FastAPI",
    category: TechCategory.Framework,
    iconify: "logos:fastapi",
    link: "https://fastapi.tiangolo.com/",
  },
  "figma": {
    id: "figma",
    name: "Figma",
    category: TechCategory.Other,
    iconify: "logos:figma",
    link: "https://www.figma.com/",
  },
  "firebase": {
    id: "firebase",
    name: "Firebase",
    category: TechCategory.Cloud,
    iconify: "logos:firebase-icon",
    link: "https://firebase.google.com/",
  },
  "flask": {
    id: "flask",
    name: "Flask",
    category: TechCategory.Framework,
    iconify: "logos:flask",
    link: "https://flask.palletsprojects.com/",
  },
  "flutter": {
    id: "flutter",
    name: "Flutter",
    category: TechCategory.Framework,
    iconify: "logos:flutter",
    link: "https://flutter.dev/",
  },
  "fortran": {
    id: "fortran",
    name: "Fortran",
    category: TechCategory.Language,
    iconify: "logos:fortran",
  },
  "gatsby": {
    id: "gatsby",
    name: "Gatsby",
    category: TechCategory.Framework,
    iconify: "logos:gatsby",
    link: "https://www.gatsbyjs.com/",
  },
  "git": {
    id: "git",
    name: "Git",
    category: TechCategory.Other,
    iconify: "logos:git-icon",
    link: "https://git-scm.com/",
  },
  "github": {
    id: "github",
    name: "GitHub",
    category: TechCategory.Other,
    iconify: "logos:github-icon",
    link: "https://github.com/",
  },
  "gitlab": {
    id: "gitlab",
    name: "GitLab",
    category: TechCategory.Other,
    iconify: "logos:gitlab-icon",
    link: "https://about.gitlab.com/",
  },
  "go": {
    id: "go",
    name: "Go",
    category: TechCategory.Language,
    iconify: "logos:go",
    link: "https://go.dev/",
  },
  "gradle": {
    id: "gradle",
    name: "Gradle",
    category: TechCategory.BuildTool,
    iconify: "logos:gradle",
  },
  "grafana": {
    id: "grafana",
    name: "Grafana",
    category: TechCategory.Other,
    iconify: "logos:grafana",
    link: "https://grafana.com/",
  },
  "graphql": {
    id: "graphql",
    name: "GraphQL",
    category: TechCategory.Language,
    iconify: "logos:graphql",
    link: "https://graphql.org/",
  },
  "gulp": {
    id: "gulp",
    name: "Gulp",
    category: TechCategory.BuildTool,
    iconify: "logos:gulp",
  },
  "haskell": {
    id: "haskell",
    name: "Haskell",
    category: TechCategory.Language,
    iconify: "logos:haskell",
    link: "https://www.haskell.org/",
  },
  "haxe": {
    id: "haxe",
    name: "Haxe",
    category: TechCategory.Language,
    iconify: "logos:haxe",
  },
  "heroku": {
    id: "heroku",
    name: "Heroku",
    category: TechCategory.Cloud,
    iconify: "logos:heroku-icon",
    link: "https://www.heroku.com/",
  },
  "hibernate": {
    id: "hibernate",
    name: "Hibernate",
    category: TechCategory.Framework,
    iconify: "logos:hibernate",
  },
  "html": {
    id: "html",
    name: "HTML",
    category: TechCategory.Language,
    iconify: "logos:html-5",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  "htmx": {
    id: "htmx",
    name: "htmx",
    category: TechCategory.Framework,
    iconify: "logos:htmx",
  },
  "instagram": {
    id: "instagram",
    name: "Instagram",
    category: TechCategory.Other,
    iconify: "logos:instagram",
  },
  "java": {
    id: "java",
    name: "Java",
    category: TechCategory.Language,
    iconify: "logos:java",
    link: "https://www.java.com/",
  },
  "js": {
    id: "js",
    name: "JavaScript",
    category: TechCategory.Language,
    iconify: "logos:javascript",
  },
  "jenkins": {
    id: "jenkins",
    name: "Jenkins",
    category: TechCategory.CICD,
    iconify: "logos:jenkins",
    link: "https://www.jenkins.io/",
  },
  "jest": {
    id: "jest",
    name: "Jest",
    category: TechCategory.Other,
    iconify: "logos:jest",
    link: "https://jestjs.io/",
  },
  "jquery": {
    id: "jquery",
    name: "jQuery",
    category: TechCategory.Library,
    iconify: "logos:jquery",
  },
  "kotlin": {
    id: "kotlin",
    name: "Kotlin",
    category: TechCategory.Language,
    iconify: "logos:kotlin",
    link: "https://kotlinlang.org/",
  },
  "ktor": {
    id: "ktor",
    name: "Ktor",
    category: TechCategory.Framework,
    iconify: "logos:ktor",
  },
  "kubernetes": {
    id: "kubernetes",
    name: "Kubernetes",
    category: TechCategory.Other,
    iconify: "logos:kubernetes",
    link: "https://kubernetes.io/",
  },
  "laravel": {
    id: "laravel",
    name: "Laravel",
    category: TechCategory.Framework,
    iconify: "logos:laravel",
    link: "https://laravel.com/",
  },
  "less": {
    id: "less",
    name: "LESS",
    category: TechCategory.Language,
    iconify: "logos:less",
    link: "https://lesscss.org/",
  },
  "lit": {
    id: "lit",
    name: "Lit",
    category: TechCategory.Framework,
    iconify: "logos:lit",
  },
  "lua": {
    id: "lua",
    name: "Lua",
    category: TechCategory.Language,
    iconify: "logos:lua",
    link: "https://www.lua.org/",
  },
  "md": {
    id: "md",
    name: "Markdown (MD)",
    category: TechCategory.Language,
    iconify: "logos:markdown",
  },
  "mastodon": {
    id: "mastodon",
    name: "Mastodon",
    category: TechCategory.Other,
    iconify: "logos:mastodon",
  },
  "mongodb": {
    id: "mongodb",
    name: "MongoDB",
    category: TechCategory.Database,
    iconify: "logos:mongodb-icon",
    link: "https://www.mongodb.com/",
  },
  "mysql": {
    id: "mysql",
    name: "MySQL",
    category: TechCategory.Database,
    iconify: "logos:mysql",
    link: "https://www.mysql.com/",
  },
  "neovim": {
    id: "neovim",
    name: "Neovim",
    category: TechCategory.Platform,
    iconify: "logos:neovim",
    link: "https://neovim.io/",
  },
  "nestjs": {
    id: "nestjs",
    name: "NestJS",
    category: TechCategory.Framework,
    iconify: "logos:nestjs",
    link: "https://nestjs.com/",
  },
  "netlify": {
    id: "netlify",
    name: "Netlify",
    category: TechCategory.Cloud,
    iconify: "logos:netlify-icon",
    link: "https://www.netlify.com/",
  },
  "nextjs": {
    id: "nextjs",
    name: "Next.js",
    category: TechCategory.Framework,
    iconify: "logos:nextjs-icon",
    link: "https://nextjs.org/",
  },
  "nginx": {
    id: "nginx",
    name: "NGINX",
    category: TechCategory.Other,
    iconify: "logos:nginx",
    link: "https://nginx.org/",
  },
  "nodejs": {
    id: "nodejs",
    name: "Node.js",
    category: TechCategory.Platform,
    iconify: "logos:nodejs-icon",
    link: "https://nodejs.org/",
  },
  "notion": {
    id: "notion",
    name: "Notion",
    category: TechCategory.Other,
    iconify: "logos:notion",
  },
  "npm": {
    id: "npm",
    name: "npm",
    category: TechCategory.BuildTool,
    iconify: "logos:npm-icon",
    link: "https://www.npmjs.com/",
  },
  "nuxtjs": {
    id: "nuxtjs",
    name: "Nuxt.js",
    category: TechCategory.Framework,
    iconify: "logos:nuxt-icon",
    link: "https://nuxt.com/",
  },
  "obsidian": {
    id: "obsidian",
    name: "Obsidian",
    category: TechCategory.Other,
    iconify: "logos:obsidian",
  },
  "ocaml": {
    id: "ocaml",
    name: "OCaml",
    category: TechCategory.Language,
    iconify: "logos:ocaml",
  },
  "openstack": {
    id: "openstack",
    name: "OpenStack",
    category: TechCategory.Cloud,
    iconify: "logos:openstack",
  },
  "p5js": {
    id: "p5js",
    name: "p5.js",
    category: TechCategory.Library,
    iconify: "logos:p5js",
  },
  "perl": {
    id: "perl",
    name: "Perl",
    category: TechCategory.Language,
    iconify: "logos:perl",
    link: "https://www.perl.org/",
  },
  "php": {
    id: "php",
    name: "PHP",
    category: TechCategory.Language,
    iconify: "logos:php",
    link: "https://www.php.net/",
  },
  "phpstorm": {
    id: "phpstorm",
    name: "PhpStorm",
    category: TechCategory.Platform,
    iconify: "logos:phpstorm",
    link: "https://www.jetbrains.com/phpstorm/",
  },
  "pinia": {
    id: "pinia",
    name: "Pinia",
    category: TechCategory.Library,
    iconify: "logos:pinia",
  },
  "planetscale": {
    id: "planetscale",
    name: "PlanetScale",
    category: TechCategory.Database,
    iconify: "logos:planetscale",
    link: "https://planetscale.com/",
  },
  "pnpm": {
    id: "pnpm",
    name: "pnpm",
    category: TechCategory.Other,
    iconify: "logos:pnpm",
    link: "https://pnpm.io/",
  },
  "postgres": {
    id: "postgres",
    name: "PostgreSQL",
    category: TechCategory.Database,
    iconify: "logos:postgresql",
    link: "https://www.postgresql.org/",
  },
  "postman": {
    id: "postman",
    name: "Postman",
    category: TechCategory.Other,
    iconify: "logos:postman",
    link: "https://www.postman.com/",
  },
  "prisma": {
    id: "prisma",
    name: "Prisma",
    category: TechCategory.Library,
    iconify: "logos:prisma",
    link: "https://www.prisma.io/",
  },
  "processing": {
    id: "processing",
    name: "Processing",
    category: TechCategory.Language,
    iconify: "logos:processing",
  },
  "prometheus": {
    id: "prometheus",
    name: "Prometheus",
    category: TechCategory.Other,
    iconify: "logos:prometheus",
    link: "https://prometheus.io/",
  },
  "pug": {
    id: "pug",
    name: "Pug",
    category: TechCategory.Language,
    iconify: "logos:pug",
  },
  "pycharm": {
    id: "pycharm",
    name: "PyCharm",
    category: TechCategory.Platform,
    iconify: "logos:pycharm",
    link: "https://www.jetbrains.com/pycharm/",
  },
  "py": {
    id: "py",
    name: "Python",
    category: TechCategory.Language,
    iconify: "logos:python",
  },
  "pytorch": {
    id: "pytorch",
    name: "PyTorch",
    category: TechCategory.Library,
    iconify: "logos:pytorch",
    link: "https://pytorch.org/",
  },
  "qt": {
    id: "qt",
    name: "Qt",
    category: TechCategory.Framework,
    iconify: "logos:qt",
  },
  "r": {
    id: "r",
    name: "R",
    category: TechCategory.Language,
    iconify: "logos:r-lang",
    link: "https://www.r-project.org/",
  },
  "rabbitmq": {
    id: "rabbitmq",
    name: "RabbitMQ",
    category: TechCategory.Other,
    iconify: "logos:rabbitmq",
    link: "https://www.rabbitmq.com/",
  },
  "rails": {
    id: "rails",
    name: "Ruby on Rails",
    category: TechCategory.Framework,
    iconify: "logos:rails",
    link: "https://rubyonrails.org/",
  },
  "react": {
    id: "react",
    name: "React",
    category: TechCategory.Framework,
    iconify: "logos:react",
    link: "https://react.dev/",
  },
  "reactivex": {
    id: "reactivex",
    name: "ReactiveX",
    category: TechCategory.Library,
    iconify: "logos:reactivex",
  },
  "redhat": {
    id: "redhat",
    name: "Red Hat",
    category: TechCategory.Platform,
    iconify: "logos:redhat",
  },
  "redis": {
    id: "redis",
    name: "Redis",
    category: TechCategory.Database,
    iconify: "logos:redis",
    link: "https://redis.io/",
  },
  "redux": {
    id: "redux",
    name: "Redux",
    category: TechCategory.Library,
    iconify: "logos:redux",
    link: "https://redux.js.org/",
  },
  "remix": {
    id: "remix",
    name: "Remix",
    category: TechCategory.Framework,
    iconify: "logos:remix",
    link: "https://remix.run/",
  },
  "replit": {
    id: "replit",
    name: "Replit",
    category: TechCategory.Platform,
    iconify: "logos:replit",
  },
  "rider": {
    id: "rider",
    name: "JetBrains Rider",
    category: TechCategory.Platform,
    iconify: "logos:rider",
  },
  "rollupjs": {
    id: "rollupjs",
    name: "Rollup.js",
    category: TechCategory.BuildTool,
    iconify: "logos:rollupjs",
    link: "https://rollupjs.org/",
  },
  "ros": {
    id: "ros",
    name: "Robot Operating System (ROS)",
    category: TechCategory.Platform,
    iconify: "logos:ros",
  },
  "ruby": {
    id: "ruby",
    name: "Ruby",
    category: TechCategory.Language,
    iconify: "logos:ruby",
    link: "https://www.ruby-lang.org/",
  },
  "rust": {
    id: "rust",
    name: "Rust",
    category: TechCategory.Language,
    iconify: "logos:rust",
    link: "https://www.rust-lang.org/",
  },
  "sass": {
    id: "sass",
    name: "Sass",
    category: TechCategory.Language,
    iconify: "logos:sass",
    link: "https://sass-lang.com/",
  },
  "spring": {
    id: "spring",
    name: "Spring Framework",
    category: TechCategory.Framework,
    iconify: "logos:spring-icon",
    link: "https://spring.io/",
  },
  "sqlite": {
    id: "sqlite",
    name: "SQLite",
    category: TechCategory.Database,
    iconify: "logos:sqlite",
    link: "https://www.sqlite.org/",
  },
  "stackoverflow": {
    id: "stackoverflow",
    name: "Stack Overflow",
    category: TechCategory.Other,
    iconify: "logos:stackoverflow",
  },
  "sublime": {
    id: "sublime",
    name: "Sublime Text",
    category: TechCategory.Platform,
    iconify: "logos:sublimetext",
  },
  "supabase": {
    id: "supabase",
    name: "Supabase",
    category: TechCategory.Database,
    iconify: "logos:supabase-icon",
    link: "https://supabase.com/",
  },
  "scala": {
    id: "scala",
    name: "Scala",
    category: TechCategory.Language,
    iconify: "logos:scala",
    link: "https://www.scala-lang.org/",
  },
  "selenium": {
    id: "selenium",
    name: "Selenium",
    category: TechCategory.Library,
    iconify: "logos:selenium",
    link: "https://www.selenium.dev/",
  },
  "sentry": {
    id: "sentry",
    name: "Sentry",
    category: TechCategory.Other,
    iconify: "logos:sentry",
    link: "https://sentry.io/",
  },
  "sequelize": {
    id: "sequelize",
    name: "Sequelize",
    category: TechCategory.Library,
    iconify: "logos:sequelize",
    link: "https://sequelize.org/",
  },
  "solidity": {
    id: "solidity",
    name: "Solidity",
    category: TechCategory.Language,
    iconify: "logos:solidity",
    link: "https://soliditylang.org/",
  },
  "solidjs": {
    id: "solidjs",
    name: "SolidJS",
    category: TechCategory.Framework,
    iconify: "logos:solidjs",
    link: "https://www.solidjs.com/",
  },
  "svelte": {
    id: "svelte",
    name: "Svelte",
    category: TechCategory.Framework,
    iconify: "logos:svelte-icon",
    link: "https://svelte.dev/",
  },
  "svg": {
    id: "svg",
    name: "SVG (Scalable Vector Graphics)",
    category: TechCategory.Other,
    iconify: "logos:svg",
    link: "https://developer.mozilla.org/en-US/docs/Web/SVG",
  },
  "swift": {
    id: "swift",
    name: "Swift",
    category: TechCategory.Language,
    iconify: "logos:swift",
    link: "https://www.swift.org/",
  },
  "symfony": {
    id: "symfony",
    name: "Symfony",
    category: TechCategory.Framework,
    iconify: "logos:symfony",
  },
  "tailwind": {
    id: "tailwind",
    name: "Tailwind CSS",
    category: TechCategory.Library,
    iconify: "logos:tailwindcss-icon",
    link: "https://tailwindcss.com/",
  },
  "tauri": {
    id: "tauri",
    name: "Tauri",
    category: TechCategory.Platform,
    iconify: "logos:tauri",
    link: "https://tauri.app/",
  },
  "tensorflow": {
    id: "tensorflow",
    name: "TensorFlow",
    category: TechCategory.Library,
    iconify: "logos:tensorflow",
    link: "https://www.tensorflow.org/",
  },
  "terraform": {
    id: "terraform",
    name: "Terraform",
    category: TechCategory.Other,
    iconify: "logos:terraform",
    link: "https://www.terraform.io/",
  },
  "threejs": {
    id: "threejs",
    name: "Three.js",
    category: TechCategory.Library,
    iconify: "logos:threejs",
  },
  "ts": {
    id: "ts",
    name: "TypeScript",
    category: TechCategory.Language,
    iconify: "logos:typescript-icon",
  },
  "ubuntu": {
    id: "ubuntu",
    name: "Ubuntu",
    category: TechCategory.Platform,
    iconify: "logos:ubuntu",
    link: "https://ubuntu.com/",
  },
  "unity": {
    id: "unity",
    name: "Unity",
    category: TechCategory.Platform,
    iconify: "logos:unity",
    link: "https://unity.com/",
  },
  "unreal": {
    id: "unreal",
    name: "Unreal Engine",
    category: TechCategory.Other,
    iconify: "logos:unrealengine",
    link: "https://www.unrealengine.com/",
  },
  "vercel": {
    id: "vercel",
    name: "Vercel",
    category: TechCategory.Platform,
    iconify: "logos:vercel-icon",
    link: "https://vercel.com/",
  },
  "vim": {
    id: "vim",
    name: "Vim",
    category: TechCategory.Other,
    iconify: "logos:vim",
    link: "https://www.vim.org/",
  },
  "visualstudio": {
    id: "visualstudio",
    name: "Visual Studio",
    category: TechCategory.Platform,
    iconify: "logos:visual-studio",
  },
  "vitest": {
    id: "vitest",
    name: "Vitest",
    category: TechCategory.Other,
    iconify: "logos:vitest",
    link: "https://vitest.dev/",
  },
  "vscode": {
    id: "vscode",
    name: "Visual Studio Code",
    category: TechCategory.Other,
    iconify: "logos:visual-studio-code",
    link: "https://code.visualstudio.com/",
  },
  "vue": {
    id: "vue",
    name: "Vue.js",
    category: TechCategory.Framework,
    iconify: "logos:vue",
    link: "https://vuejs.org/",
  },
  "wasm": {
    id: "wasm",
    name: "WebAssembly (WASM)",
    category: TechCategory.Other,
    iconify: "logos:webassembly",
  },
  "webflow": {
    id: "webflow",
    name: "Webflow",
    category: TechCategory.Platform,
    iconify: "logos:webflow",
  },
  "webpack": {
    id: "webpack",
    name: "Webpack",
    category: TechCategory.BuildTool,
    iconify: "logos:webpack",
    link: "https://webpack.js.org/",
  },
  "webstorm": {
    id: "webstorm",
    name: "WebStorm",
    category: TechCategory.Platform,
    iconify: "logos:webstorm",
    link: "https://www.jetbrains.com/webstorm/",
  },
  "wordpress": {
    id: "wordpress",
    name: "WordPress",
    category: TechCategory.Other,
    iconify: "logos:wordpress",
    link: "https://wordpress.org/",
  },
  "yarn": {
    id: "yarn",
    name: "Yarn",
    category: TechCategory.Other,
    iconify: "logos:yarn",
    link: "https://yarnpkg.com/",
  },
  "zig": {
    id: "zig",
    name: "Zig",
    category: TechCategory.Language,
    iconify: "logos:zig",
  },
  "gleam": {
    id: "gleam",
    name: "Gleam",
    category: TechCategory.Language,
    iconify: "logos:gleam"
  },
  "elm": {
    id: "elm",
    name: "Elm",
    category: TechCategory.Language,
    iconify: "logos:elm"
  },
  "erlang": {
    id: "erlang",
    name: "Erlang",
    category: TechCategory.Language,
    iconify: "logos:erlang"
  },
  "qwik": {
    id: "qwik",
    name: "Qwik",
    category: TechCategory.Framework,
    iconify: "logos:qwik"
  },
  "preact": {
    id: "preact",
    name: "Preact",
    category: TechCategory.Framework,
    iconify: "logos:preact"
  },
  "analog": {
    id: "analog",
    name: "Analog",
    category: TechCategory.Framework,
    iconify: "logos:analog"
  },
  "hono": {
    id: "hono",
    name: "Hono",
    category: TechCategory.Framework,
    iconify: "logos:hono"
  },
  "mariadb": {
    id: "mariadb",
    name: "MariaDB",
    category: TechCategory.Database,
    iconify: "logos:mariadb"
  },
  "influxdb": {
    id: "influxdb",
    name: "InfluxDB",
    category: TechCategory.Database,
    iconify: "logos:influxdb"
  },
  "neon": {
    id: "neon",
    name: "Neon",
    category: TechCategory.Database,
    iconify: "logos:neon"
  },
  "upstash": {
    id: "upstash",
    name: "Upstash",
    category: TechCategory.Database,
    iconify: "logos:upstash"
  },
  "fly": {
    id: "fly",
    name: "Fly.io",
    category: TechCategory.Cloud,
    iconify: "logos:fly"
  },
  "cloudflare-workers": {
    id: "cloudflare-workers",
    name: "Cloudflare Workers",
    category: TechCategory.Cloud,
    iconify: "logos:cloudflare-workers"
  },
  "esbuild": {
    id: "esbuild",
    name: "esbuild",
    category: TechCategory.BuildTool,
    iconify: "logos:esbuild"
  },
  "parcel": {
    id: "parcel",
    name: "Parcel",
    category: TechCategory.BuildTool,
    iconify: "logos:parcel-icon"
  },
  "turbopack": {
    id: "turbopack",
    name: "Turbopack",
    category: TechCategory.BuildTool,
    iconify: "logos:turbopack"
  },
  "turborepo": {
    id: "turborepo",
    name: "Turborepo",
    category: TechCategory.BuildTool,
    iconify: "logos:turborepo-icon"
  },
  "nx": {
    id: "nx",
    name: "Nx",
    category: TechCategory.BuildTool,
    iconify: "logos:nx"
  },
  "composer": {
    id: "composer",
    name: "Composer",
    category: TechCategory.BuildTool,
    iconify: "logos:composer"
  },
  "circleci": {
    id: "circleci",
    name: "CircleCI",
    category: TechCategory.CICD,
    iconify: "logos:circleci"
  },
  "playwright": {
    id: "playwright",
    name: "Playwright",
    category: TechCategory.Testing,
    iconify: "logos:playwright"
  },
  "storybook": {
    id: "storybook",
    name: "Storybook",
    category: TechCategory.Testing,
    iconify: "logos:storybook-icon"
  },
  "testinglibrary": {
    id: "testinglibrary",
    name: "Testing Library",
    category: TechCategory.Testing,
    iconify: "logos:testing-library"
  },
  "mocha": {
    id: "mocha",
    name: "Mocha",
    category: TechCategory.Testing,
    iconify: "logos:mocha"
  },
  "trpc": {
    id: "trpc",
    name: "tRPC",
    category: TechCategory.Library,
    iconify: "logos:trpc"
  },
  "mobx": {
    id: "mobx",
    name: "MobX",
    category: TechCategory.Library,
    iconify: "logos:mobx"
  },
  "jotai": {
    id: "jotai",
    name: "Jotai",
    category: TechCategory.Library,
    iconify: "logos:jotai"
  },
  "drizzle": {
    id: "drizzle",
    name: "Drizzle ORM",
    category: TechCategory.Library,
    iconify: "logos:drizzle"
  },
  "payload": {
    id: "payload",
    name: "Payload CMS",
    category: TechCategory.Other,
    iconify: "logos:payload"
  },
  "sanity": {
    id: "sanity",
    name: "Sanity",
    category: TechCategory.Other,
    iconify: "logos:sanity"
  },
  "strapi": {
    id: "strapi",
    name: "Strapi",
    category: TechCategory.Other,
    iconify: "logos:strapi-icon"
  },
  "auth0": {
    id: "auth0",
    name: "Auth0",
    category: TechCategory.Other,
    iconify: "logos:auth0-icon"
  },
  "datadog": {
    id: "datadog",
    name: "Datadog",
    category: TechCategory.Monitoring,
    iconify: "logos:datadog"
  },
  "openai": {
    id: "openai",
    name: "OpenAI",
    category: TechCategory.Other,
    iconify: "logos:openai-icon"
  },
  "anthropic": {
    id: "anthropic",
    name: "Anthropic",
    category: TechCategory.Other,
    iconify: "logos:anthropic"
  }
} as const satisfies Record<string, TechItem>;

// Array format for backward compatibility
export const TECH_STACK_LIST: TechItem[] = Object.values(TECH_STACK);
