import { TechCategory, type TechItem } from "@/types/tech";

export const TECH_STACK_LIST: TechItem[] = [
  { id: "ableton", name: "Ableton Live", category: TechCategory.Other },
  { id: "activitypub", name: "ActivityPub", category: TechCategory.Other },
  { id: "actix", name: "Actix", category: TechCategory.Framework },
  { id: "adonis", name: "AdonisJS", category: TechCategory.Framework },
  { id: "ae", name: "Adobe After Effects", category: TechCategory.Other },
  { id: "aiscript", name: "AI Script", category: TechCategory.Other },
  { id: "alpinejs", name: "Alpine.js", category: TechCategory.Framework },
  { id: "anaconda", name: "Anaconda", category: TechCategory.Platform },
  { id: "androidstudio", name: "Android Studio", category: TechCategory.Platform },
  { id: "angular", name: "Angular", category: TechCategory.Framework },
  { id: "ansible", name: "Ansible", category: TechCategory.Platform },
  { id: "apollo", name: "Apollo GraphQL", category: TechCategory.Library },
  { id: "apple", name: "Apple", category: TechCategory.Platform },
  { id: "appwrite", name: "Appwrite", category: TechCategory.Cloud },
  { id: "arch", name: "Arch Linux", category: TechCategory.Platform },
  { id: "arduino", name: "Arduino", category: TechCategory.Platform },
  { id: "astro", name: "Astro", category: TechCategory.Framework },
  { id: "atom", name: "Atom", category: TechCategory.Platform },
  { id: "au", name: "AU (Audio Units)", category: TechCategory.Other },
  { id: "autocad", name: "AutoCAD", category: TechCategory.Other },
  { id: "aws", name: "Amazon Web Services", category: TechCategory.Cloud },
  { id: "azul", name: "Azul Systems", category: TechCategory.Platform },
  { id: "azure", name: "Microsoft Azure", category: TechCategory.Cloud },
  { id: "babel", name: "Babel", category: TechCategory.Library },
  { id: "bash", name: "Bash", category: TechCategory.Language },
  { id: "bevy", name: "Bevy", category: TechCategory.Framework },
  { id: "bitbucket", name: "Bitbucket", category: TechCategory.CICD },
  { id: "blender", name: "Blender", category: TechCategory.Other },
  { id: "bootstrap", name: "Bootstrap", category: TechCategory.Library },
  { id: "bsd", name: "BSD", category: TechCategory.Platform },
  { id: "bun", name: "Bun", category: TechCategory.Platform },
  { id: "c", name: "C", category: TechCategory.Language },
  { id: "cs", name: "C#", category: TechCategory.Language },
  { id: "cpp", name: "C++", category: TechCategory.Language },
  { id: "crystal", name: "Crystal", category: TechCategory.Language },
  { id: "cassandra", name: "Apache Cassandra", category: TechCategory.Database },
  { id: "clion", name: "CLion", category: TechCategory.Platform },
  { id: "clojure", name: "Clojure", category: TechCategory.Language },
  { id: "cloudflare", name: "Cloudflare", category: TechCategory.Cloud },
  { id: "cmake", name: "CMake", category: TechCategory.Library },
  { id: "codepen", name: "CodePen", category: TechCategory.Platform },
  { id: "coffeescript", name: "CoffeeScript", category: TechCategory.Language },
  { id: "css", name: "CSS", category: TechCategory.Language },
  { id: "cypress", name: "Cypress", category: TechCategory.Library },
  { id: "d3", name: "D3.js", category: TechCategory.Library },
  { id: "dart", name: "Dart", category: TechCategory.Language },
  { id: "debian", name: "Debian", category: TechCategory.Platform },
  { id: "deno", name: "Deno", category: TechCategory.Platform },
  { id: "devto", name: "DEV Community", category: TechCategory.Other },
  { id: "discord", name: "Discord", category: TechCategory.Other },
  { id: "bots", name: "Discord Bots", category: TechCategory.Other },
  { id: "discordjs", name: "Discord.js", category: TechCategory.Library },
  { id: "django", name: "Django", category: TechCategory.Framework },
  { id: "docker", name: "Docker", category: TechCategory.Platform },
  { id: "dotnet", name: ".NET", category: TechCategory.Framework },
  { id: "dynamodb", name: "Amazon DynamoDB", category: TechCategory.Database },
  { id: "eclipse", name: "Eclipse", category: TechCategory.Platform },
  { id: "elasticsearch", name: "Elasticsearch", category: TechCategory.Database },
  { id: "electron", name: "Electron", category: TechCategory.Framework },
  { id: "elixir", name: "Elixir", category: TechCategory.Language },
  { id: "emacs", name: "GNU Emacs", category: TechCategory.Platform },
  { id: "ember", name: "Ember.js", category: TechCategory.Framework },
  { id: "emotion", name: "Emotion", category: TechCategory.Library },
  { id: "express", name: "Express.js", category: TechCategory.Framework },
  { id: "fastapi", name: "FastAPI", category: TechCategory.Framework },
  { id: "fediverse", name: "Fediverse", category: TechCategory.Other },
  { id: "figma", name: "Figma", category: TechCategory.Other },
  { id: "firebase", name: "Firebase", category: TechCategory.Cloud },
  { id: "flask", name: "Flask", category: TechCategory.Framework },
  { id: "flutter", name: "Flutter", category: TechCategory.Framework },
  { id: "fortran", name: "Fortran", category: TechCategory.Language },
  { id: "gamemakerstudio", name: "GameMaker Studio", category: TechCategory.Platform },
  { id: "gatsby", name: "Gatsby", category: TechCategory.Framework },
  { id: "gcp", name: "Google Cloud Platform", category: TechCategory.Cloud },
  { id: "git", name: "Git", category: TechCategory.Other },
  { id: "github", name: "GitHub", category: TechCategory.Other },
  { id: "githubactions", name: "GitHub Actions", category: TechCategory.CICD },
  { id: "gitlab", name: "GitLab", category: TechCategory.Other },
  { id: "gmail", name: "Gmail", category: TechCategory.Other },
  { id: "go", name: "Go", category: TechCategory.Language },
  { id: "gradle", name: "Gradle", category: TechCategory.BuildTool },
  { id: "godot", name: "Godot Engine", category: TechCategory.Platform },
  { id: "grafana", name: "Grafana", category: TechCategory.Other },
  { id: "graphql", name: "GraphQL", category: TechCategory.Language },
  { id: "gtk", name: "GTK", category: TechCategory.Framework },
  { id: "gulp", name: "Gulp", category: TechCategory.BuildTool },
  { id: "haskell", name: "Haskell", category: TechCategory.Language },
  { id: "haxe", name: "Haxe", category: TechCategory.Language },
  { id: "heroku", name: "Heroku", category: TechCategory.Cloud },
  { id: "hibernate", name: "Hibernate", category: TechCategory.Framework },
  { id: "html", name: "HTML", category: TechCategory.Language },
  { id: "htmx", name: "htmx", category: TechCategory.Framework },
  { id: "idea", name: "IntelliJ IDEA", category: TechCategory.Platform },
  { id: "ai", name: "Artificial Intelligence (AI)", category: TechCategory.Other },
  { id: "instagram", name: "Instagram", category: TechCategory.Other },
  { id: "ipfs", name: "InterPlanetary File System (IPFS)", category: TechCategory.Other },
  { id: "java", name: "Java", category: TechCategory.Language },
  { id: "js", name: "JavaScript", category: TechCategory.Language },
  { id: "jenkins", name: "Jenkins", category: TechCategory.CICD },
  { id: "jest", name: "Jest", category: TechCategory.Other },
  { id: "jquery", name: "jQuery", category: TechCategory.Library },
  { id: "kafka", name: "Apache Kafka", category: TechCategory.Other },
  { id: "kali", name: "Kali Linux", category: TechCategory.Platform },
  { id: "kotlin", name: "Kotlin", category: TechCategory.Language },
  { id: "ktor", name: "Ktor", category: TechCategory.Framework },
  { id: "kubernetes", name: "Kubernetes", category: TechCategory.Other },
  { id: "laravel", name: "Laravel", category: TechCategory.Framework },
  { id: "latex", name: "LaTeX", category: TechCategory.Other },
  { id: "less", name: "LESS", category: TechCategory.Language },
  { id: "linkedin", name: "LinkedIn", category: TechCategory.Other },
  { id: "linux", name: "Linux", category: TechCategory.Platform },
  { id: "lit", name: "Lit", category: TechCategory.Framework },
  { id: "lua", name: "Lua", category: TechCategory.Language },
  { id: "md", name: "Markdown (MD)", category: TechCategory.Language },
  { id: "mastodon", name: "Mastodon", category: TechCategory.Other },
  { id: "materialui", name: "Material-UI", category: TechCategory.Library },
  { id: "matlab", name: "MATLAB", category: TechCategory.Language },
  { id: "maven", name: "Apache Maven", category: TechCategory.BuildTool },
  { id: "mint", name: "Mint", category: TechCategory.Platform },
  { id: "misskey", name: "Misskey", category: TechCategory.Other },
  { id: "mongodb", name: "MongoDB", category: TechCategory.Database },
  { id: "mysql", name: "MySQL", category: TechCategory.Database },
  { id: "neovim", name: "Neovim", category: TechCategory.Platform },
  { id: "nestjs", name: "NestJS", category: TechCategory.Framework },
  { id: "netlify", name: "Netlify", category: TechCategory.Cloud },
  { id: "nextjs", name: "Next.js", category: TechCategory.Framework },
  { id: "nginx", name: "NGINX", category: TechCategory.Other },
  { id: "nim", name: "Nim", category: TechCategory.Language },
  { id: "nix", name: "Nix", category: TechCategory.Platform },
  { id: "nodejs", name: "Node.js", category: TechCategory.Platform },
  { id: "notion", name: "Notion", category: TechCategory.Other },
  { id: "npm", name: "npm", category: TechCategory.BuildTool },
  { id: "nuxtjs", name: "Nuxt.js", category: TechCategory.Framework },
  { id: "obsidian", name: "Obsidian", category: TechCategory.Other },
  { id: "ocaml", name: "OCaml", category: TechCategory.Language },
  { id: "octave", name: "GNU Octave", category: TechCategory.Language },
  { id: "opencv", name: "OpenCV", category: TechCategory.Library },
  { id: "openshift", name: "OpenShift", category: TechCategory.Cloud },
  { id: "openstack", name: "OpenStack", category: TechCategory.Cloud },
  { id: "p5js", name: "p5.js", category: TechCategory.Library },
  { id: "perl", name: "Perl", category: TechCategory.Language },
  { id: "powershell", name: "PowerShell", category: TechCategory.Language },
  { id: "php", name: "PHP", category: TechCategory.Language },
  { id: "phpstorm", name: "PhpStorm", category: TechCategory.Platform },
  { id: "pinia", name: "Pinia", category: TechCategory.Library },
  { id: "pkl", name: "PKL", category: TechCategory.Other },
  { id: "plan9", name: "Plan 9", category: TechCategory.Platform },
  { id: "planetscale", name: "PlanetScale", category: TechCategory.Database },
  { id: "pnpm", name: "pnpm", category: TechCategory.Other },
  { id: "postgres", name: "PostgreSQL", category: TechCategory.Database },
  { id: "postman", name: "Postman", category: TechCategory.Other },
  { id: "ps", name: "Adobe PhotoShop", category: TechCategory.Other },
  { id: "pr", name: "Adobe Premiere Pro", category: TechCategory.Other },
  { id: "prisma", name: "Prisma", category: TechCategory.Library },
  { id: "processing", name: "Processing", category: TechCategory.Language },
  { id: "prometheus", name: "Prometheus", category: TechCategory.Other },
  { id: "pug", name: "Pug", category: TechCategory.Language },
  { id: "pycharm", name: "PyCharm", category: TechCategory.Platform },
  { id: "py", name: "Python", category: TechCategory.Language },
  { id: "pytorch", name: "PyTorch", category: TechCategory.Library },
  { id: "qt", name: "Qt", category: TechCategory.Framework },
  { id: "r", name: "R", category: TechCategory.Language },
  { id: "rabbitmq", name: "RabbitMQ", category: TechCategory.Other },
  { id: "rails", name: "Ruby on Rails", category: TechCategory.Framework },
  { id: "raspberrypi", name: "Raspberry Pi", category: TechCategory.Other },
  { id: "react", name: "React", category: TechCategory.Framework },
  { id: "reactivex", name: "ReactiveX", category: TechCategory.Library },
  { id: "redhat", name: "Red Hat", category: TechCategory.Platform },
  { id: "redis", name: "Redis", category: TechCategory.Database },
  { id: "redux", name: "Redux", category: TechCategory.Library },
  { id: "regex", name: "Regular Expressions (Regex)", category: TechCategory.Other },
  { id: "remix", name: "Remix", category: TechCategory.Framework },
  { id: "replit", name: "Replit", category: TechCategory.Platform },
  { id: "rider", name: "JetBrains Rider", category: TechCategory.Platform },
  { id: "robloxstudio", name: "Roblox Studio", category: TechCategory.Platform },
  { id: "rocket", name: "Rocket", category: TechCategory.Framework },
  { id: "rollupjs", name: "Rollup.js", category: TechCategory.BuildTool },
  { id: "ros", name: "Robot Operating System (ROS)", category: TechCategory.Platform },
  { id: "ruby", name: "Ruby", category: TechCategory.Language },
  { id: "rust", name: "Rust", category: TechCategory.Language },
  { id: "sass", name: "Sass", category: TechCategory.Language },
  { id: "spring", name: "Spring Framework", category: TechCategory.Framework },
  { id: "sqlite", name: "SQLite", category: TechCategory.Database },
  { id: "stackoverflow", name: "Stack Overflow", category: TechCategory.Other },
  { id: "styledcomponents", name: "Styled Components", category: TechCategory.Library },
  { id: "sublime", name: "Sublime Text", category: TechCategory.Platform },
  { id: "supabase", name: "Supabase", category: TechCategory.Database },
  { id: "scala", name: "Scala", category: TechCategory.Language },
  { id: "sklearn", name: "scikit-learn", category: TechCategory.Library },
  { id: "selenium", name: "Selenium", category: TechCategory.Library },
  { id: "sentry", name: "Sentry", category: TechCategory.Other },
  { id: "sequelize", name: "Sequelize", category: TechCategory.Library },
  { id: "sketchup", name: "SketchUp", category: TechCategory.Platform },
  { id: "solidity", name: "Solidity", category: TechCategory.Language },
  { id: "solidjs", name: "SolidJS", category: TechCategory.Framework },
  { id: "svelte", name: "Svelte", category: TechCategory.Framework },
  { id: "svg", name: "SVG (Scalable Vector Graphics)", category: TechCategory.Other },
  { id: "swift", name: "Swift", category: TechCategory.Language },
  { id: "symfony", name: "Symfony", category: TechCategory.Framework },
  { id: "tailwind", name: "Tailwind CSS", category: TechCategory.Library },
  { id: "tauri", name: "Tauri", category: TechCategory.Platform },
  { id: "tensorflow", name: "TensorFlow", category: TechCategory.Library },
  { id: "terraform", name: "Terraform", category: TechCategory.Other },
  { id: "threejs", name: "Three.js", category: TechCategory.Library },
  { id: "twitter", name: "Twitter", category: TechCategory.Other },
  { id: "ts", name: "TypeScript", category: TechCategory.Language },
  { id: "ubuntu", name: "Ubuntu", category: TechCategory.Platform },
  { id: "unity", name: "Unity", category: TechCategory.Platform },
  { id: "unreal", name: "Unreal Engine", category: TechCategory.Other },
  { id: "v", name: "V", category: TechCategory.Language },
  { id: "vala", name: "Vala", category: TechCategory.Language },
  { id: "vercel", name: "Vercel", category: TechCategory.Platform },
  { id: "vim", name: "Vim", category: TechCategory.Other },
  { id: "visualstudio", name: "Visual Studio", category: TechCategory.Platform },
  { id: "vite", name: "Vite", category: TechCategory.BuildTool },
  { id: "vitest", name: "Vitest", category: TechCategory.Other },
  { id: "vscode", name: "Visual Studio Code", category: TechCategory.Other },
  { id: "vscodium", name: "VSCodium", category: TechCategory.Other },
  { id: "vue", name: "Vue.js", category: TechCategory.Framework },
  { id: "vuetify", name: "Vuetify", category: TechCategory.Library },
  { id: "wasm", name: "WebAssembly (WASM)", category: TechCategory.Other },
  { id: "webflow", name: "Webflow", category: TechCategory.Platform },
  { id: "webpack", name: "Webpack", category: TechCategory.BuildTool },
  { id: "webstorm", name: "WebStorm", category: TechCategory.Platform },
  { id: "windicss", name: "Windi CSS", category: TechCategory.Library },
  { id: "windows", name: "Windows", category: TechCategory.Platform },
  { id: "wordpress", name: "WordPress", category: TechCategory.Other },
  { id: "workers", name: "Workers", category: TechCategory.Other },
  { id: "xd", name: "Adobe XD", category: TechCategory.Other },
  { id: "yarn", name: "Yarn", category: TechCategory.Other },
  { id: "zig", name: "Zig", category: TechCategory.Language }
];
