import type { TechId, TechItem } from "@/types/tech";
import { TechCategory } from "@/types/tech";

/**
 * Tech Stack Data
 *
 * Single source of truth for all technology information.
 * Includes icon mappings and links in one place.
 *
 * @see https://icon-sets.iconify.design/ for available icons
 */
export const TECH_STACK = {
  "activitypub": {
    id: "activitypub",
    name: "ActivityPub",
    category: TechCategory.Other,
    iconify: "simple-icons:activitypub",
  },
  "actix": {
    id: "actix",
    name: "Actix",
    category: TechCategory.Framework,
    iconify: "simple-icons:actix",
  },
  "adonis": {
    id: "adonis",
    name: "AdonisJS",
    category: TechCategory.Framework,
    iconify: "logos:adonisjs-icon",
  },
  "ae": {
    id: "ae",
    name: "Adobe After Effects",
    category: TechCategory.Other,
    iconify: "simple-icons:adobeaftereffects",
  },
  "alpinejs": {
    id: "alpinejs",
    name: "Alpine.js",
    category: TechCategory.Framework,
    iconify: "logos:alpinejs-icon",
  },
  "anaconda": {
    id: "anaconda",
    name: "Anaconda",
    category: TechCategory.Platform,
    iconify: "simple-icons:anaconda",
  },
  "androidstudio": {
    id: "androidstudio",
    name: "Android Studio",
    category: TechCategory.Platform,
    iconify: "simple-icons:androidstudio",
  },
  "angular": {
    id: "angular",
    name: "Angular",
    category: TechCategory.Framework,
    iconify: "logos:angular-icon",
    link: "https://angular.io/",
  },
  "ansible": {
    id: "ansible",
    name: "Ansible",
    category: TechCategory.Platform,
    iconify: "logos:ansible",
    link: "https://www.ansible.com/",
  },
  "apollo": {
    id: "apollo",
    name: "Apollo GraphQL",
    category: TechCategory.Library,
    iconify: "simple-icons:apollographql",
  },
  "apple": {
    id: "apple",
    name: "Apple",
    category: TechCategory.Platform,
    iconify: "logos:apple",
  },
  "appwrite": {
    id: "appwrite",
    name: "Appwrite",
    category: TechCategory.Cloud,
    iconify: "logos:appwrite",
  },
  "arch": {
    id: "arch",
    name: "Arch Linux",
    category: TechCategory.Platform,
    iconify: "logos:archlinux",
  },
  "arduino": {
    id: "arduino",
    name: "Arduino",
    category: TechCategory.Platform,
    iconify: "logos:arduino",
  },
  "astro": {
    id: "astro",
    name: "Astro",
    category: TechCategory.Framework,
    iconify: "logos:astro-icon",
    link: "https://astro.build/",
  },
  "atom": {
    id: "atom",
    name: "Atom",
    category: TechCategory.Platform,
    iconify: "logos:atom",
  },
  "au": {
    id: "au",
    name: "AU (Audio Units)",
    category: TechCategory.Other,
    iconify: "simple-icons:adobeaudition",
  },
  "autocad": {
    id: "autocad",
    name: "AutoCAD",
    category: TechCategory.Other,
    iconify: "simple-icons:autocad",
  },
  "aws": {
    id: "aws",
    name: "Amazon Web Services",
    category: TechCategory.Cloud,
    iconify: "devicon:amazonwebservices",
    link: "https://aws.amazon.com/",
  },
  "azure": {
    id: "azure",
    name: "Microsoft Azure",
    category: TechCategory.Cloud,
    iconify: "devicon:azure",
    link: "https://azure.microsoft.com/",
  },
  "babel": {
    id: "babel",
    name: "Babel",
    category: TechCategory.Library,
    iconify: "logos:babel",
    link: "https://babeljs.io/",
  },
  "bash": {
    id: "bash",
    name: "Bash",
    category: TechCategory.Language,
    iconify: "logos:bash",
    link: "https://www.gnu.org/software/bash/",
  },
  "bevy": {
    id: "bevy",
    name: "Bevy",
    category: TechCategory.Framework,
    iconify: "simple-icons:bevy",
  },
  "bitbucket": {
    id: "bitbucket",
    name: "Bitbucket",
    category: TechCategory.CICD,
    iconify: "logos:bitbucket",
  },
  "blender": {
    id: "blender",
    name: "Blender",
    category: TechCategory.Other,
    iconify: "logos:blender",
  },
  "bootstrap": {
    id: "bootstrap",
    name: "Bootstrap",
    category: TechCategory.Library,
    iconify: "logos:bootstrap",
    link: "https://getbootstrap.com/",
  },
  "bsd": {
    id: "bsd",
    name: "BSD",
    category: TechCategory.Platform,
    iconify: "logos:freebsd",
  },
  "bun": {
    id: "bun",
    name: "Bun",
    category: TechCategory.Platform,
    iconify: "logos:bun",
    link: "https://bun.sh/",
  },
  "c": {
    id: "c",
    name: "C",
    category: TechCategory.Language,
    iconify: "logos:c",
    link: "https://en.cppreference.com/w/c",
  },
  "cs": {
    id: "cs",
    name: "C#",
    category: TechCategory.Language,
    iconify: "logos:c-sharp",
    link: "https://docs.microsoft.com/en-us/dotnet/csharp/",
  },
  "cpp": {
    id: "cpp",
    name: "C++",
    category: TechCategory.Language,
    iconify: "logos:c-plusplus",
    link: "https://en.cppreference.com/w/cpp",
  },
  "crystal": {
    id: "crystal",
    name: "Crystal",
    category: TechCategory.Language,
    iconify: "logos:crystal",
  },
  "cassandra": {
    id: "cassandra",
    name: "Apache Cassandra",
    category: TechCategory.Database,
    iconify: "simple-icons:apachecassandra",
    link: "https://cassandra.apache.org/",
  },
  "clion": {
    id: "clion",
    name: "CLion",
    category: TechCategory.Platform,
    iconify: "logos:clion",
  },
  "clojure": {
    id: "clojure",
    name: "Clojure",
    category: TechCategory.Language,
    iconify: "logos:clojure",
    link: "https://clojure.org/",
  },
  "cloudflare": {
    id: "cloudflare",
    name: "Cloudflare",
    category: TechCategory.Cloud,
    iconify: "logos:cloudflare",
    link: "https://www.cloudflare.com/",
  },
  "cmake": {
    id: "cmake",
    name: "CMake",
    category: TechCategory.Library,
    iconify: "simple-icons:cmake",
  },
  "codepen": {
    id: "codepen",
    name: "CodePen",
    category: TechCategory.Platform,
    iconify: "devicon:codepen",
  },
  "coffeescript": {
    id: "coffeescript",
    name: "CoffeeScript",
    category: TechCategory.Language,
    iconify: "logos:coffeescript",
  },
  "css": {
    id: "css",
    name: "CSS",
    category: TechCategory.Language,
    iconify: "logos:css-3",
    link: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  "cypress": {
    id: "cypress",
    name: "Cypress",
    category: TechCategory.Library,
    iconify: "logos:cypress-icon",
    link: "https://www.cypress.io/",
  },
  "d3": {
    id: "d3",
    name: "D3.js",
    category: TechCategory.Library,
    iconify: "simple-icons:d3dotjs",
  },
  "dart": {
    id: "dart",
    name: "Dart",
    category: TechCategory.Language,
    iconify: "logos:dart",
    link: "https://dart.dev/",
  },
  "debian": {
    id: "debian",
    name: "Debian",
    category: TechCategory.Platform,
    iconify: "logos:debian",
    link: "https://www.debian.org/",
  },
  "deno": {
    id: "deno",
    name: "Deno",
    category: TechCategory.Platform,
    iconify: "logos:deno",
  },
  "devto": {
    id: "devto",
    name: "DEV Community",
    category: TechCategory.Other,
    iconify: "simple-icons:devdotto",
  },
  "discord": {
    id: "discord",
    name: "Discord",
    category: TechCategory.Other,
    iconify: "simple-icons:discord",
  },
  "bots": {
    id: "bots",
    name: "Discord Bots",
    category: TechCategory.Other,
    iconify: "simple-icons:discord",
  },
  "discordjs": {
    id: "discordjs",
    name: "Discord.js",
    category: TechCategory.Library,
    iconify: "logos:discordjs",
  },
  "django": {
    id: "django",
    name: "Django",
    category: TechCategory.Framework,
    iconify: "logos:django-icon",
    link: "https://www.djangoproject.com/",
  },
  "docker": {
    id: "docker",
    name: "Docker",
    category: TechCategory.Platform,
    iconify: "logos:docker-icon",
    link: "https://www.docker.com/",
  },
  "dotnet": {
    id: "dotnet",
    name: ".NET",
    category: TechCategory.Framework,
    iconify: "logos:dotnet",
  },
  "dynamodb": {
    id: "dynamodb",
    name: "Amazon DynamoDB",
    category: TechCategory.Database,
    iconify: "logos:aws-dynamodb",
    link: "https://aws.amazon.com/dynamodb/",
  },
  "eclipse": {
    id: "eclipse",
    name: "Eclipse",
    category: TechCategory.Platform,
    iconify: "logos:eclipseide",
  },
  "elasticsearch": {
    id: "elasticsearch",
    name: "Elasticsearch",
    category: TechCategory.Database,
    iconify: "logos:elasticsearch",
    link: "https://www.elastic.co/",
  },
  "electron": {
    id: "electron",
    name: "Electron",
    category: TechCategory.Framework,
    iconify: "logos:electron",
    link: "https://www.electronjs.org/",
  },
  "elixir": {
    id: "elixir",
    name: "Elixir",
    category: TechCategory.Language,
    iconify: "devicon:elixir",
    link: "https://elixir-lang.org/",
  },
  "emacs": {
    id: "emacs",
    name: "GNU Emacs",
    category: TechCategory.Platform,
    iconify: "simple-icons:gnuemacs",
  },
  "ember": {
    id: "ember",
    name: "Ember.js",
    category: TechCategory.Framework,
    iconify: "logos:ember",
  },
  "express": {
    id: "express",
    name: "Express.js",
    category: TechCategory.Framework,
    iconify: "logos:express",
    link: "https://expressjs.com/",
  },
  "fastapi": {
    id: "fastapi",
    name: "FastAPI",
    category: TechCategory.Framework,
    iconify: "logos:fastapi",
    link: "https://fastapi.tiangolo.com/",
  },
  "figma": {
    id: "figma",
    name: "Figma",
    category: TechCategory.Other,
    iconify: "logos:figma",
    link: "https://www.figma.com/",
  },
  "firebase": {
    id: "firebase",
    name: "Firebase",
    category: TechCategory.Cloud,
    iconify: "logos:firebase-icon",
    link: "https://firebase.google.com/",
  },
  "flask": {
    id: "flask",
    name: "Flask",
    category: TechCategory.Framework,
    iconify: "logos:flask",
    link: "https://flask.palletsprojects.com/",
  },
  "flutter": {
    id: "flutter",
    name: "Flutter",
    category: TechCategory.Framework,
    iconify: "logos:flutter",
    link: "https://flutter.dev/",
  },
  "fortran": {
    id: "fortran",
    name: "Fortran",
    category: TechCategory.Language,
    iconify: "logos:fortran",
  },
  "gamemakerstudio": {
    id: "gamemakerstudio",
    name: "GameMaker Studio",
    category: TechCategory.Platform,
    iconify: "simple-icons:gamemaker",
  },
  "gatsby": {
    id: "gatsby",
    name: "Gatsby",
    category: TechCategory.Framework,
    iconify: "logos:gatsby",
    link: "https://www.gatsbyjs.com/",
  },
  "gcp": {
    id: "gcp",
    name: "Google Cloud Platform",
    category: TechCategory.Cloud,
    iconify: "simple-icons:googlecloud",
    link: "https://cloud.google.com/",
  },
  "git": {
    id: "git",
    name: "Git",
    category: TechCategory.Other,
    iconify: "logos:git-icon",
    link: "https://git-scm.com/",
  },
  "github": {
    id: "github",
    name: "GitHub",
    category: TechCategory.Other,
    iconify: "logos:github-icon",
    link: "https://github.com/",
  },
  "githubactions": {
    id: "githubactions",
    name: "GitHub Actions",
    category: TechCategory.CICD,
    iconify: "simple-icons:githubactions",
    link: "https://github.com/features/actions",
  },
  "gitlab": {
    id: "gitlab",
    name: "GitLab",
    category: TechCategory.Other,
    iconify: "logos:gitlab-icon",
    link: "https://about.gitlab.com/",
  },
  "gmail": {
    id: "gmail",
    name: "Gmail",
    category: TechCategory.Other,
    iconify: "simple-icons:gmail",
  },
  "go": {
    id: "go",
    name: "Go",
    category: TechCategory.Language,
    iconify: "logos:go",
    link: "https://go.dev/",
  },
  "gradle": {
    id: "gradle",
    name: "Gradle",
    category: TechCategory.BuildTool,
    iconify: "logos:gradle",
  },
  "godot": {
    id: "godot",
    name: "Godot Engine",
    category: TechCategory.Platform,
    iconify: "simple-icons:godotengine",
    link: "https://godotengine.org/",
  },
  "grafana": {
    id: "grafana",
    name: "Grafana",
    category: TechCategory.Other,
    iconify: "logos:grafana",
    link: "https://grafana.com/",
  },
  "graphql": {
    id: "graphql",
    name: "GraphQL",
    category: TechCategory.Language,
    iconify: "logos:graphql",
    link: "https://graphql.org/",
  },
  "gtk": {
    id: "gtk",
    name: "GTK",
    category: TechCategory.Framework,
    iconify: "simple-icons:gtk",
  },
  "gulp": {
    id: "gulp",
    name: "Gulp",
    category: TechCategory.BuildTool,
    iconify: "logos:gulp",
  },
  "haskell": {
    id: "haskell",
    name: "Haskell",
    category: TechCategory.Language,
    iconify: "logos:haskell",
    link: "https://www.haskell.org/",
  },
  "haxe": {
    id: "haxe",
    name: "Haxe",
    category: TechCategory.Language,
    iconify: "logos:haxe",
  },
  "heroku": {
    id: "heroku",
    name: "Heroku",
    category: TechCategory.Cloud,
    iconify: "logos:heroku-icon",
    link: "https://www.heroku.com/",
  },
  "hibernate": {
    id: "hibernate",
    name: "Hibernate",
    category: TechCategory.Framework,
    iconify: "logos:hibernate",
  },
  "html": {
    id: "html",
    name: "HTML",
    category: TechCategory.Language,
    iconify: "logos:html-5",
    link: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  "htmx": {
    id: "htmx",
    name: "htmx",
    category: TechCategory.Framework,
    iconify: "logos:htmx",
  },
  "idea": {
    id: "idea",
    name: "IntelliJ IDEA",
    category: TechCategory.Platform,
    iconify: "simple-icons:intellijidea",
    link: "https://www.jetbrains.com/idea/",
  },
  "ai": {
    id: "ai",
    name: "Artificial Intelligence (AI)",
    category: TechCategory.Other,
    iconify: "simple-icons:adobeillustrator",
  },
  "instagram": {
    id: "instagram",
    name: "Instagram",
    category: TechCategory.Other,
    iconify: "logos:instagram",
  },
  "ipfs": {
    id: "ipfs",
    name: "InterPlanetary File System (IPFS)",
    category: TechCategory.Other,
    iconify: "simple-icons:ipfs",
  },
  "java": {
    id: "java",
    name: "Java",
    category: TechCategory.Language,
    iconify: "logos:java",
    link: "https://www.java.com/",
  },
  "js": {
    id: "js",
    name: "JavaScript",
    category: TechCategory.Language,
    iconify: "logos:javascript",
  },
  "jenkins": {
    id: "jenkins",
    name: "Jenkins",
    category: TechCategory.CICD,
    iconify: "logos:jenkins",
    link: "https://www.jenkins.io/",
  },
  "jest": {
    id: "jest",
    name: "Jest",
    category: TechCategory.Other,
    iconify: "logos:jest",
    link: "https://jestjs.io/",
  },
  "jquery": {
    id: "jquery",
    name: "jQuery",
    category: TechCategory.Library,
    iconify: "logos:jquery",
  },
  "kafka": {
    id: "kafka",
    name: "Apache Kafka",
    category: TechCategory.Other,
    iconify: "simple-icons:apachekafka",
    link: "https://kafka.apache.org/",
  },
  "kali": {
    id: "kali",
    name: "Kali Linux",
    category: TechCategory.Platform,
    iconify: "simple-icons:kalilinux",
  },
  "kotlin": {
    id: "kotlin",
    name: "Kotlin",
    category: TechCategory.Language,
    iconify: "logos:kotlin",
    link: "https://kotlinlang.org/",
  },
  "ktor": {
    id: "ktor",
    name: "Ktor",
    category: TechCategory.Framework,
    iconify: "logos:ktor",
  },
  "kubernetes": {
    id: "kubernetes",
    name: "Kubernetes",
    category: TechCategory.Other,
    iconify: "logos:kubernetes",
    link: "https://kubernetes.io/",
  },
  "laravel": {
    id: "laravel",
    name: "Laravel",
    category: TechCategory.Framework,
    iconify: "logos:laravel",
    link: "https://laravel.com/",
  },
  "latex": {
    id: "latex",
    name: "LaTeX",
    category: TechCategory.Other,
    iconify: "simple-icons:latex",
    link: "https://www.latex-project.org/",
  },
  "less": {
    id: "less",
    name: "LESS",
    category: TechCategory.Language,
    iconify: "logos:less",
    link: "https://lesscss.org/",
  },
  "linkedin": {
    id: "linkedin",
    name: "LinkedIn",
    category: TechCategory.Other,
    iconify: "devicon:linkedin",
  },
  "linux": {
    id: "linux",
    name: "Linux",
    category: TechCategory.Platform,
    iconify: "simple-icons:linux",
    link: "https://www.linux.org/",
  },
  "lit": {
    id: "lit",
    name: "Lit",
    category: TechCategory.Framework,
    iconify: "logos:lit",
  },
  "lua": {
    id: "lua",
    name: "Lua",
    category: TechCategory.Language,
    iconify: "logos:lua",
    link: "https://www.lua.org/",
  },
  "md": {
    id: "md",
    name: "Markdown (MD)",
    category: TechCategory.Language,
    iconify: "logos:markdown",
  },
  "mastodon": {
    id: "mastodon",
    name: "Mastodon",
    category: TechCategory.Other,
    iconify: "logos:mastodon",
  },
  "materialui": {
    id: "materialui",
    name: "Material-UI",
    category: TechCategory.Library,
    iconify: "simple-icons:mui",
    link: "https://mui.com/",
  },
  "matlab": {
    id: "matlab",
    name: "MATLAB",
    category: TechCategory.Language,
    iconify: "devicon:matlab",
  },
  "maven": {
    id: "maven",
    name: "Apache Maven",
    category: TechCategory.BuildTool,
    iconify: "simple-icons:apachemaven",
  },
  "mint": {
    id: "mint",
    name: "Mint",
    category: TechCategory.Platform,
    iconify: "simple-icons:linuxmint",
  },
  "misskey": {
    id: "misskey",
    name: "Misskey",
    category: TechCategory.Other,
    iconify: "simple-icons:misskey",
  },
  "mongodb": {
    id: "mongodb",
    name: "MongoDB",
    category: TechCategory.Database,
    iconify: "logos:mongodb-icon",
    link: "https://www.mongodb.com/",
  },
  "mysql": {
    id: "mysql",
    name: "MySQL",
    category: TechCategory.Database,
    iconify: "logos:mysql",
    link: "https://www.mysql.com/",
  },
  "neovim": {
    id: "neovim",
    name: "Neovim",
    category: TechCategory.Platform,
    iconify: "logos:neovim",
    link: "https://neovim.io/",
  },
  "nestjs": {
    id: "nestjs",
    name: "NestJS",
    category: TechCategory.Framework,
    iconify: "logos:nestjs",
    link: "https://nestjs.com/",
  },
  "netlify": {
    id: "netlify",
    name: "Netlify",
    category: TechCategory.Cloud,
    iconify: "logos:netlify-icon",
    link: "https://www.netlify.com/",
  },
  "nextjs": {
    id: "nextjs",
    name: "Next.js",
    category: TechCategory.Framework,
    iconify: "logos:nextjs-icon",
    link: "https://nextjs.org/",
  },
  "nginx": {
    id: "nginx",
    name: "NGINX",
    category: TechCategory.Other,
    iconify: "logos:nginx",
    link: "https://nginx.org/",
  },
  "nim": {
    id: "nim",
    name: "Nim",
    category: TechCategory.Language,
    iconify: "devicon:nim",
  },
  "nix": {
    id: "nix",
    name: "Nix",
    category: TechCategory.Platform,
    iconify: "simple-icons:nixos",
  },
  "nodejs": {
    id: "nodejs",
    name: "Node.js",
    category: TechCategory.Platform,
    iconify: "logos:nodejs-icon",
    link: "https://nodejs.org/",
  },
  "notion": {
    id: "notion",
    name: "Notion",
    category: TechCategory.Other,
    iconify: "logos:notion",
  },
  "npm": {
    id: "npm",
    name: "npm",
    category: TechCategory.BuildTool,
    iconify: "logos:npm-icon",
    link: "https://www.npmjs.com/",
  },
  "nuxtjs": {
    id: "nuxtjs",
    name: "Nuxt.js",
    category: TechCategory.Framework,
    iconify: "logos:nuxt-icon",
    link: "https://nuxt.com/",
  },
  "obsidian": {
    id: "obsidian",
    name: "Obsidian",
    category: TechCategory.Other,
    iconify: "logos:obsidian",
  },
  "ocaml": {
    id: "ocaml",
    name: "OCaml",
    category: TechCategory.Language,
    iconify: "logos:ocaml",
  },
  "octave": {
    id: "octave",
    name: "GNU Octave",
    category: TechCategory.Language,
    iconify: "simple-icons:octave",
  },
  "opencv": {
    id: "opencv",
    name: "OpenCV",
    category: TechCategory.Library,
    iconify: "simple-icons:opencv",
  },
  "openshift": {
    id: "openshift",
    name: "OpenShift",
    category: TechCategory.Cloud,
    iconify: "logos:redhatopenshift",
  },
  "openstack": {
    id: "openstack",
    name: "OpenStack",
    category: TechCategory.Cloud,
    iconify: "logos:openstack",
  },
  "p5js": {
    id: "p5js",
    name: "p5.js",
    category: TechCategory.Library,
    iconify: "logos:p5js",
  },
  "perl": {
    id: "perl",
    name: "Perl",
    category: TechCategory.Language,
    iconify: "logos:perl",
    link: "https://www.perl.org/",
  },
  "powershell": {
    id: "powershell",
    name: "PowerShell",
    category: TechCategory.Language,
    iconify: "devicon:powershell",
  },
  "php": {
    id: "php",
    name: "PHP",
    category: TechCategory.Language,
    iconify: "logos:php",
    link: "https://www.php.net/",
  },
  "phpstorm": {
    id: "phpstorm",
    name: "PhpStorm",
    category: TechCategory.Platform,
    iconify: "logos:phpstorm",
    link: "https://www.jetbrains.com/phpstorm/",
  },
  "pinia": {
    id: "pinia",
    name: "Pinia",
    category: TechCategory.Library,
    iconify: "logos:pinia",
  },
  "planetscale": {
    id: "planetscale",
    name: "PlanetScale",
    category: TechCategory.Database,
    iconify: "logos:planetscale",
    link: "https://planetscale.com/",
  },
  "pnpm": {
    id: "pnpm",
    name: "pnpm",
    category: TechCategory.Other,
    iconify: "logos:pnpm",
    link: "https://pnpm.io/",
  },
  "postgres": {
    id: "postgres",
    name: "PostgreSQL",
    category: TechCategory.Database,
    iconify: "logos:postgresql",
    link: "https://www.postgresql.org/",
  },
  "postman": {
    id: "postman",
    name: "Postman",
    category: TechCategory.Other,
    iconify: "logos:postman",
    link: "https://www.postman.com/",
  },
  "ps": {
    id: "ps",
    name: "Adobe PhotoShop",
    category: TechCategory.Other,
    iconify: "simple-icons:adobephotoshop",
  },
  "pr": {
    id: "pr",
    name: "Adobe Premiere Pro",
    category: TechCategory.Other,
    iconify: "simple-icons:adobepremierepro",
  },
  "prisma": {
    id: "prisma",
    name: "Prisma",
    category: TechCategory.Library,
    iconify: "logos:prisma",
    link: "https://www.prisma.io/",
  },
  "processing": {
    id: "processing",
    name: "Processing",
    category: TechCategory.Language,
    iconify: "logos:processing",
  },
  "prometheus": {
    id: "prometheus",
    name: "Prometheus",
    category: TechCategory.Other,
    iconify: "logos:prometheus",
    link: "https://prometheus.io/",
  },
  "pug": {
    id: "pug",
    name: "Pug",
    category: TechCategory.Language,
    iconify: "logos:pug",
  },
  "pycharm": {
    id: "pycharm",
    name: "PyCharm",
    category: TechCategory.Platform,
    iconify: "logos:pycharm",
    link: "https://www.jetbrains.com/pycharm/",
  },
  "py": {
    id: "py",
    name: "Python",
    category: TechCategory.Language,
    iconify: "logos:python",
  },
  "pytorch": {
    id: "pytorch",
    name: "PyTorch",
    category: TechCategory.Library,
    iconify: "logos:pytorch",
    link: "https://pytorch.org/",
  },
  "qt": {
    id: "qt",
    name: "Qt",
    category: TechCategory.Framework,
    iconify: "logos:qt",
  },
  "r": {
    id: "r",
    name: "R",
    category: TechCategory.Language,
    iconify: "logos:r-lang",
    link: "https://www.r-project.org/",
  },
  "rabbitmq": {
    id: "rabbitmq",
    name: "RabbitMQ",
    category: TechCategory.Other,
    iconify: "logos:rabbitmq",
    link: "https://www.rabbitmq.com/",
  },
  "rails": {
    id: "rails",
    name: "Ruby on Rails",
    category: TechCategory.Framework,
    iconify: "logos:rails",
    link: "https://rubyonrails.org/",
  },
  "raspberrypi": {
    id: "raspberrypi",
    name: "Raspberry Pi",
    category: TechCategory.Other,
    iconify: "simple-icons:raspberrypi",
  },
  "react": {
    id: "react",
    name: "React",
    category: TechCategory.Framework,
    iconify: "logos:react",
    link: "https://react.dev/",
  },
  "reactivex": {
    id: "reactivex",
    name: "ReactiveX",
    category: TechCategory.Library,
    iconify: "logos:reactivex",
  },
  "redhat": {
    id: "redhat",
    name: "Red Hat",
    category: TechCategory.Platform,
    iconify: "logos:redhat",
  },
  "redis": {
    id: "redis",
    name: "Redis",
    category: TechCategory.Database,
    iconify: "logos:redis",
    link: "https://redis.io/",
  },
  "redux": {
    id: "redux",
    name: "Redux",
    category: TechCategory.Library,
    iconify: "logos:redux",
    link: "https://redux.js.org/",
  },
  "regex": {
    id: "regex",
    name: "Regular Expressions (Regex)",
    category: TechCategory.Other,
    iconify: "devicon:regex",
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions",
  },
  "remix": {
    id: "remix",
    name: "Remix",
    category: TechCategory.Framework,
    iconify: "logos:remix",
    link: "https://remix.run/",
  },
  "replit": {
    id: "replit",
    name: "Replit",
    category: TechCategory.Platform,
    iconify: "logos:replit",
  },
  "rider": {
    id: "rider",
    name: "JetBrains Rider",
    category: TechCategory.Platform,
    iconify: "logos:rider",
  },
  "robloxstudio": {
    id: "robloxstudio",
    name: "Roblox Studio",
    category: TechCategory.Platform,
    iconify: "logos:robloxstudio",
  },
  "rocket": {
    id: "rocket",
    name: "Rocket",
    category: TechCategory.Framework,
    iconify: "simple-icons:rocket",
  },
  "rollupjs": {
    id: "rollupjs",
    name: "Rollup.js",
    category: TechCategory.BuildTool,
    iconify: "logos:rollupjs",
    link: "https://rollupjs.org/",
  },
  "ros": {
    id: "ros",
    name: "Robot Operating System (ROS)",
    category: TechCategory.Platform,
    iconify: "logos:ros",
  },
  "ruby": {
    id: "ruby",
    name: "Ruby",
    category: TechCategory.Language,
    iconify: "logos:ruby",
    link: "https://www.ruby-lang.org/",
  },
  "rust": {
    id: "rust",
    name: "Rust",
    category: TechCategory.Language,
    iconify: "logos:rust",
    link: "https://www.rust-lang.org/",
  },
  "sass": {
    id: "sass",
    name: "Sass",
    category: TechCategory.Language,
    iconify: "logos:sass",
    link: "https://sass-lang.com/",
  },
  "spring": {
    id: "spring",
    name: "Spring Framework",
    category: TechCategory.Framework,
    iconify: "logos:spring-icon",
    link: "https://spring.io/",
  },
  "sqlite": {
    id: "sqlite",
    name: "SQLite",
    category: TechCategory.Database,
    iconify: "logos:sqlite",
    link: "https://www.sqlite.org/",
  },
  "stackoverflow": {
    id: "stackoverflow",
    name: "Stack Overflow",
    category: TechCategory.Other,
    iconify: "logos:stackoverflow",
  },
  "styledcomponents": {
    id: "styledcomponents",
    name: "Styled Components",
    category: TechCategory.Library,
    iconify: "simple-icons:styledcomponents",
    link: "https://styled-components.com/",
  },
  "sublime": {
    id: "sublime",
    name: "Sublime Text",
    category: TechCategory.Platform,
    iconify: "logos:sublimetext",
  },
  "supabase": {
    id: "supabase",
    name: "Supabase",
    category: TechCategory.Database,
    iconify: "logos:supabase-icon",
    link: "https://supabase.com/",
  },
  "scala": {
    id: "scala",
    name: "Scala",
    category: TechCategory.Language,
    iconify: "logos:scala",
    link: "https://www.scala-lang.org/",
  },
  "sklearn": {
    id: "sklearn",
    name: "scikit-learn",
    category: TechCategory.Library,
    iconify: "simple-icons:scikitlearn",
  },
  "selenium": {
    id: "selenium",
    name: "Selenium",
    category: TechCategory.Library,
    iconify: "logos:selenium",
    link: "https://www.selenium.dev/",
  },
  "sentry": {
    id: "sentry",
    name: "Sentry",
    category: TechCategory.Other,
    iconify: "logos:sentry",
    link: "https://sentry.io/",
  },
  "sequelize": {
    id: "sequelize",
    name: "Sequelize",
    category: TechCategory.Library,
    iconify: "logos:sequelize",
    link: "https://sequelize.org/",
  },
  "sketchup": {
    id: "sketchup",
    name: "SketchUp",
    category: TechCategory.Platform,
    iconify: "simple-icons:sketchup",
  },
  "solidity": {
    id: "solidity",
    name: "Solidity",
    category: TechCategory.Language,
    iconify: "logos:solidity",
    link: "https://soliditylang.org/",
  },
  "solidjs": {
    id: "solidjs",
    name: "SolidJS",
    category: TechCategory.Framework,
    iconify: "logos:solidjs",
    link: "https://www.solidjs.com/",
  },
  "svelte": {
    id: "svelte",
    name: "Svelte",
    category: TechCategory.Framework,
    iconify: "logos:svelte-icon",
    link: "https://svelte.dev/",
  },
  "svg": {
    id: "svg",
    name: "SVG (Scalable Vector Graphics)",
    category: TechCategory.Other,
    iconify: "logos:svg",
    link: "https://developer.mozilla.org/en-US/docs/Web/SVG",
  },
  "swift": {
    id: "swift",
    name: "Swift",
    category: TechCategory.Language,
    iconify: "logos:swift",
    link: "https://www.swift.org/",
  },
  "symfony": {
    id: "symfony",
    name: "Symfony",
    category: TechCategory.Framework,
    iconify: "logos:symfony",
  },
  "tailwind": {
    id: "tailwind",
    name: "Tailwind CSS",
    category: TechCategory.Library,
    iconify: "logos:tailwindcss-icon",
    link: "https://tailwindcss.com/",
  },
  "tauri": {
    id: "tauri",
    name: "Tauri",
    category: TechCategory.Platform,
    iconify: "logos:tauri",
    link: "https://tauri.app/",
  },
  "tensorflow": {
    id: "tensorflow",
    name: "TensorFlow",
    category: TechCategory.Library,
    iconify: "logos:tensorflow",
    link: "https://www.tensorflow.org/",
  },
  "terraform": {
    id: "terraform",
    name: "Terraform",
    category: TechCategory.Other,
    iconify: "logos:terraform",
    link: "https://www.terraform.io/",
  },
  "threejs": {
    id: "threejs",
    name: "Three.js",
    category: TechCategory.Library,
    iconify: "logos:threejs",
  },
  "twitter": {
    id: "twitter",
    name: "Twitter",
    category: TechCategory.Other,
    iconify: "devicon:twitter",
  },
  "ts": {
    id: "ts",
    name: "TypeScript",
    category: TechCategory.Language,
    iconify: "logos:typescript-icon",
  },
  "ubuntu": {
    id: "ubuntu",
    name: "Ubuntu",
    category: TechCategory.Platform,
    iconify: "logos:ubuntu",
    link: "https://ubuntu.com/",
  },
  "unity": {
    id: "unity",
    name: "Unity",
    category: TechCategory.Platform,
    iconify: "logos:unity",
    link: "https://unity.com/",
  },
  "unreal": {
    id: "unreal",
    name: "Unreal Engine",
    category: TechCategory.Other,
    iconify: "logos:unrealengine",
    link: "https://www.unrealengine.com/",
  },
  "v": {
    id: "v",
    name: "V",
    category: TechCategory.Language,
    iconify: "simple-icons:v",
  },
  "vala": {
    id: "vala",
    name: "Vala",
    category: TechCategory.Language,
    iconify: "devicon:vala",
  },
  "vercel": {
    id: "vercel",
    name: "Vercel",
    category: TechCategory.Platform,
    iconify: "logos:vercel-icon",
    link: "https://vercel.com/",
  },
  "vim": {
    id: "vim",
    name: "Vim",
    category: TechCategory.Other,
    iconify: "logos:vim",
    link: "https://www.vim.org/",
  },
  "visualstudio": {
    id: "visualstudio",
    name: "Visual Studio",
    category: TechCategory.Platform,
    iconify: "devicon:visualstudio",
  },
  "vite": {
    id: "vite",
    name: "Vite",
    category: TechCategory.BuildTool,
    iconify: "simple-icons:vite",
    link: "https://vitejs.dev/",
  },
  "vitest": {
    id: "vitest",
    name: "Vitest",
    category: TechCategory.Other,
    iconify: "logos:vitest",
    link: "https://vitest.dev/",
  },
  "vscode": {
    id: "vscode",
    name: "Visual Studio Code",
    category: TechCategory.Other,
    iconify: "devicon:vscode",
    link: "https://code.visualstudio.com/",
  },
  "vscodium": {
    id: "vscodium",
    name: "VSCodium",
    category: TechCategory.Other,
    iconify: "simple-icons:vscodium",
  },
  "vue": {
    id: "vue",
    name: "Vue.js",
    category: TechCategory.Framework,
    iconify: "logos:vue",
    link: "https://vuejs.org/",
  },
  "vuetify": {
    id: "vuetify",
    name: "Vuetify",
    category: TechCategory.Library,
    iconify: "simple-icons:vuetify",
  },
  "wasm": {
    id: "wasm",
    name: "WebAssembly (WASM)",
    category: TechCategory.Other,
    iconify: "logos:webassembly",
  },
  "webflow": {
    id: "webflow",
    name: "Webflow",
    category: TechCategory.Platform,
    iconify: "logos:webflow",
  },
  "webpack": {
    id: "webpack",
    name: "Webpack",
    category: TechCategory.BuildTool,
    iconify: "logos:webpack",
    link: "https://webpack.js.org/",
  },
  "webstorm": {
    id: "webstorm",
    name: "WebStorm",
    category: TechCategory.Platform,
    iconify: "logos:webstorm",
    link: "https://www.jetbrains.com/webstorm/",
  },
  "windicss": {
    id: "windicss",
    name: "Windi CSS",
    category: TechCategory.Library,
    iconify: "simple-icons:windicss",
  },
  "windows": {
    id: "windows",
    name: "Windows",
    category: TechCategory.Platform,
    iconify: "simple-icons:windows",
    link: "https://www.microsoft.com/windows",
  },
  "wordpress": {
    id: "wordpress",
    name: "WordPress",
    category: TechCategory.Other,
    iconify: "logos:wordpress",
    link: "https://wordpress.org/",
  },
  "workers": {
    id: "workers",
    name: "Workers",
    category: TechCategory.Other,
    iconify: "simple-icons:cloudflareworkers",
  },
  "xd": {
    id: "xd",
    name: "Adobe XD",
    category: TechCategory.Other,
    iconify: "simple-icons:adobexd",
  },
  "yarn": {
    id: "yarn",
    name: "Yarn",
    category: TechCategory.Other,
    iconify: "logos:yarn",
    link: "https://yarnpkg.com/",
  },
  "zig": {
    id: "zig",
    name: "Zig",
    category: TechCategory.Language,
    iconify: "logos:zig",
  }
} as const satisfies Record<string, TechItem>;

// Type-safe tech ID list
export const TECH_IDS = Object.keys(TECH_STACK) as TechId[];

// Array format for backward compatibility
export const TECH_STACK_LIST: TechItem[] = Object.values(TECH_STACK);

// Type-safe getter with Record cast for indexing
export function getTechById(id: TechId): TechItem {
  return (TECH_STACK as Record<string, TechItem>)[id];
}

// Safe getter with validation
export function getTechByIdSafe(id: string): TechItem | undefined {
  return (TECH_STACK as Record<string, TechItem>)[id];
}
